# (PART) CoreStats 1: Simple hypothesis testing {.unnumbered}

# Introduction

## Objectives
:::objectives
**Aim: To carry out basic one and two sample statistical tests.**

By the end of this section and practical participants should be able to achieve the following for each of the listed tests:

1.	Understand what the purpose of each test is
2.	Perform the test in R
3.	Interpret the test output
4.	Understand under what assumptions/conditions each test is appropriate
5.	Check for those assumptions
:::

The tests covered in this practical are:

-	One-sample tests
-	One sample t-test
-	Wilcoxon one-sample signed-rank
-	Two-sample tests
-	Student’s t-test
-	Mann-Whitney U test 
-	Paired t-test
-	Wilcoxon signed-rank test

## Background

This practical does not focus on the underlying mathematical theory of the tests although the demonstrators will be happy to answer any questions.
For each test there will be a section explaining its purpose, a section explaining how to perform the test in R, a section explaining the results that have been output to the screen, and a section covering the assumptions required to perform the test.
