<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 5 Two-sample tests | Core Statistics in R</title>
<meta name="author" content="Matt Castle and Martin van Rongen">
<meta name="description" content="5.1 Objectives  Questions When do I perform a two-sample test? Which two-sample tests are there and what are the assumptions? How do I interpret and present the results of the tests? Objectives...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 5 Two-sample tests | Core Statistics in R">
<meta property="og:type" content="book">
<meta property="og:description" content="5.1 Objectives  Questions When do I perform a two-sample test? Which two-sample tests are there and what are the assumptions? How do I interpret and present the results of the tests? Objectives...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 5 Two-sample tests | Core Statistics in R">
<meta name="twitter:description" content="5.1 Objectives  Questions When do I perform a two-sample test? Which two-sample tests are there and what are the assumptions? How do I interpret and present the results of the tests? Objectives...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="uni-title"> <img src="img/main-logo-homepage.svg" alt="Biostatistics Initiative" style="padding: 10px" width="250" height="53">
</div>

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Core Statistics in R</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <div class="searchbar">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>
      </div>
      <div class="menu-items" width="100%">
      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Overview</a></li>
<li class="book-part">CoreStats 1: Simple hypothesis testing</li>
<li><a class="" href="cs1-intro.html"><span class="header-section-number">2</span> Introduction</a></li>
<li class="book-part">CoreStats 1 (Practicals)</li>
<li><a class="" href="introduction.html"><span class="header-section-number">3</span> Introduction</a></li>
<li><a class="" href="cs1-one-sample-tests.html"><span class="header-section-number">4</span> One-sample tests</a></li>
<li><a class="active" href="cs1-two-sample.html"><span class="header-section-number">5</span> Two-sample tests</a></li>
<li class="book-part">CoreStats 2: Single categorical predictors</li>
<li><a class="" href="cs2-intro.html"><span class="header-section-number">6</span> Introduction</a></li>
<li class="book-part">CoreStats 2 (Practicals)</li>
<li><a class="" href="introduction-1.html"><span class="header-section-number">7</span> Introduction</a></li>
<li><a class="" href="cs2-anova.html"><span class="header-section-number">8</span> ANOVA</a></li>
<li><a class="" href="kruskal-wallis-test.html"><span class="header-section-number">9</span> Kruskal-Wallis test</a></li>
<li class="book-part">CoreStats 3: Single continuous predictors</li>
<li><a class="" href="cs3-intro.html"><span class="header-section-number">10</span> Introduction</a></li>
<li class="book-part">CoreStats 3 (Practicals)</li>
<li><a class="" href="introduction-2.html"><span class="header-section-number">11</span> Introduction</a></li>
<li><a class="" href="correlation-coefficients.html"><span class="header-section-number">12</span> Correlation coefficients</a></li>
<li><a class="" href="linear-regression.html"><span class="header-section-number">13</span> Linear regression</a></li>
<li class="book-part">CoreStats 4: Two predictor variables</li>
<li><a class="" href="cs4-intro.html"><span class="header-section-number">14</span> Introduction</a></li>
<li class="book-part">CoreStats 4 (Practicals)</li>
<li><a class="" href="introduction-3.html"><span class="header-section-number">15</span> Introduction</a></li>
<li><a class="" href="two-way-anova.html"><span class="header-section-number">16</span> Two-way ANOVA</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/cambiotraining/corestats_in_r">View book source <i class="fab fa-github"></i></a></p>
        </div>
        </nav>
</div>
      
    </div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="cs1-two-sample" class="section level1" number="5">
<h1>
<span class="header-section-number">5</span> Two-sample tests<a class="anchor" aria-label="anchor" href="#cs1-two-sample"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-2" class="section level2" number="5.1">
<h2>
<span class="header-section-number">5.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-2"><i class="fas fa-link"></i></a>
</h2>
<div class="objectives">
<p><strong>Questions</strong></p>
<ul>
<li>When do I perform a two-sample test?</li>
<li>Which two-sample tests are there and what are the assumptions?</li>
<li>How do I interpret and present the results of the tests?</li>
</ul>
<p><strong>Objectives</strong></p>
<ul>
<li>Set out your hypothesis for two-sample continuous data</li>
<li>Determine the correct data format to perform a two-sample test in R</li>
<li>Summarise and visualise the data</li>
<li>Check underlying assumptions (normality, homogeneity of variance)</li>
<li>Be able to choose an appropriate two-sample test and run it in R</li>
<li>Be able to interpret and report the results</li>
</ul>
</div>
</div>
<div id="purpose-and-aim-1" class="section level2" number="5.2">
<h2>
<span class="header-section-number">5.2</span> Purpose and aim<a class="anchor" aria-label="anchor" href="#purpose-and-aim-1"><i class="fas fa-link"></i></a>
</h2>
<p>These tests are used when we have two samples of continuous data where we are trying to find out if the samples came from the same parent distribution or not. This essentially boils down to finding out if there is a difference in the means of the two samples.</p>
</div>
<div id="two-sample-choosing-a-test" class="section level2" number="5.3">
<h2>
<span class="header-section-number">5.3</span> Choosing a test<a class="anchor" aria-label="anchor" href="#two-sample-choosing-a-test"><i class="fas fa-link"></i></a>
</h2>
<p>There are five key tests that can be used to deal with two samples. Choosing which test to use depends upon which key assumptions are satisfied by your sample data and this effectively boils down to answering four questions about your samples:</p>
<ol style="list-style-type: decimal">
<li>Are the samples normally distributed? (Yes/No)</li>
<li>How big are your samples? (&lt;30 data points or &gt;30 data points)</li>
<li>Are the samples paired? (Yes/No)</li>
<li>Do the samples have the same variance? (Yes/No)</li>
</ol>
<p>There are two sets of tests to consider depending on your answers to questions 1 and 2. If your data are normally distributed or if you have big samples then you need to look at the parametric tests. If your data are not normally distributed <em>and</em> your sample size is small, then you need to look at non-parametric tests (see Figure <a href="cs1-two-sample.html#fig:fig-cs1-diagram-test">5.1</a>. Questions 3 and 4 then help you pick the specific test to use, which is summarised in Figure <a href="cs1-two-sample.html#fig:fig-cs1-diagram-which-test">5.2</a>.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:fig-cs1-diagram-test"></span>
<img src="img/cs1-diagram-test.svg" alt="Category of test"><p class="caption">
Figure 5.1: Category of test
</p>
</div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:fig-cs1-diagram-which-test"></span>
<img src="img/cs1-diagram-which-test.svg" alt="Which test to use"><p class="caption">
Figure 5.2: Which test to use
</p>
</div>
<ol style="list-style-type: decimal">
<li>Testing whether a sample comes from a normal distribution was covered in <a href="cs1-one-sample-tests.html#cs1-one-sample-tests">One-sample tests</a>. You need to visualise your data and/or use the Shapiro-Wilk test.</li>
<li>The size of the sample makes things easier. Because of maths (specifically due to something called the central limit theorem which I am not even going to attempt to touch upon here) if you have large samples then you can use the tests that assume normality of the parent population (Student’s t-test, Welch’s t-test and the paired t-test) even if your parent populations are certainly not normal. If you really want to understand exactly why this works, then you will have to do some more rigorous mathematics. So, for the moment I’m going to say that it’s OK to take these facts on faith and just trust me on this.</li>
<li>Paired samples mean that for every data point in one sample there is a matching data point in the other sample that is linked to it in some inextricable way. A typical example would involve a group of 20 test subjects being measured before and after some experiment. Providing that the experiment didn’t do anything fatal to the test subjects then the data would consist of two samples; 20 pre-experiment measurements and 20 post-experiment measurements. However, because the same test subjects were used then each pre-experiment data point can be matched exactly to one of the post-experiment data points. In this sense the two samples are said to be “paired.”</li>
<li>There are a couple of tests (Bartlett’s test and Levene’s test) that can be used to see if two samples come from distributions with the same variance. These will be covered in a later section.</li>
<li>Resampling techniques aren’t covered in this course and require a mixture of statistical understanding and programming skill. Ask a demonstrator (or Google it 😉) if you want to know more.</li>
</ol>
<div id="data-format" class="section level3" number="5.3.1">
<h3>
<span class="header-section-number">5.3.1</span> Data format<a class="anchor" aria-label="anchor" href="#data-format"><i class="fas fa-link"></i></a>
</h3>
<p>For two samples the data can be stored in one of three formats in R:</p>
<ol style="list-style-type: decimal">
<li>as two separate vectors,</li>
<li>in a stacked data frame,</li>
<li>or in an unstacked data frame/list.</li>
</ol>
<p>Two separate vectors case is (hopefully) obvious.</p>
<p>When using a data frame we have different options to organise our data. The best way of formatting data in R is by using <a href="https://r4ds.had.co.nz/tidy-data.html">the tidy data format</a>.</p>
<div class="highlight">
<p><strong>Tidy data</strong> has the following properties:</p>
<ul>
<li>Each variable has its own column</li>
<li>Each observation has its own row</li>
<li>Each value has its own cell</li>
</ul>
</div>
<p>Stacked form (or <a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">long format data</a>) is where the data is arranged in such a way that each variable (thing that we measured) has its own column. If we consider a dataset containing meerkat weights (in g) from two different countries then a stacked format of the data would look like:</p>
<div class="inline-table"><table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:left;">
country
</th>
<th style="text-align:right;">
weight
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Botswana
</td>
<td style="text-align:right;">
514
</td>
</tr>
<tr>
<td style="text-align:left;">
Botswana
</td>
<td style="text-align:right;">
568
</td>
</tr>
<tr>
<td style="text-align:left;">
Botswana
</td>
<td style="text-align:right;">
519
</td>
</tr>
<tr>
<td style="text-align:left;">
Uganda
</td>
<td style="text-align:right;">
624
</td>
</tr>
<tr>
<td style="text-align:left;">
Uganda
</td>
<td style="text-align:right;">
662
</td>
</tr>
<tr>
<td style="text-align:left;">
Uganda
</td>
<td style="text-align:right;">
633
</td>
</tr>
</tbody>
</table></div>
<p>In the unstacked (or <a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">wide format</a>) form a variable (measured thing) is present in more than one column. For example, let’s say we measured meerkat weight in two countries over a period of years. We could then organise our data in such a way that for each year the measured values are split by country:</p>
<div class="inline-table"><table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:right;">
year
</th>
<th style="text-align:right;">
Botswana
</th>
<th style="text-align:right;">
Uganda
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
1990
</td>
<td style="text-align:right;">
514
</td>
<td style="text-align:right;">
624
</td>
</tr>
<tr>
<td style="text-align:right;">
1992
</td>
<td style="text-align:right;">
568
</td>
<td style="text-align:right;">
662
</td>
</tr>
<tr>
<td style="text-align:right;">
1995
</td>
<td style="text-align:right;">
519
</td>
<td style="text-align:right;">
633
</td>
</tr>
</tbody>
</table></div>
<p>Having tidy data is the easiest way of doing analyses in R and I would strongly encourage you all to start adopting this format as standard for data collection and processing.</p>
</div>
</div>
<div id="cs1-students-t-test" class="section level2" number="5.4">
<h2>
<span class="header-section-number">5.4</span> Student’s t-test<a class="anchor" aria-label="anchor" href="#cs1-students-t-test"><i class="fas fa-link"></i></a>
</h2>
<p>For this test we assume that both sample data sets are normally distributed and have equal variance. We test to see if the means of the two samples differ significantly from each other.</p>
<div class="note">
<p>The language used in this section is slightly different to that used in section <a href="cs1-one-sample-tests.html#cs1-one-sample-tests">4</a>. Although the language used in section <a href="cs1-one-sample-tests.html#cs1-one-sample-tests">4</a> was technically more correct, the sentences are somewhat more onerous to read. Here I’ve opted for an easier reading style at the expense of technical accuracy. Please feel free to re-write this section (at your own leisure).</p>
</div>
<div id="section-commands-2" class="section level3" number="5.4.1">
<h3>
<span class="header-section-number">5.4.1</span> Section commands<a class="anchor" aria-label="anchor" href="#section-commands-2"><i class="fas fa-link"></i></a>
</h3>
<p>New commands used in this section:</p>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="50%">
<col width="50%">
</colgroup>
<thead><tr class="header">
<th align="left">Function</th>
<th align="left">Description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left"><code>aggregate</code></td>
<td align="left">Splits the data into subsets, computes summary statistics for each, and returns the result in a convenient form</td>
</tr>
<tr class="even">
<td align="left"><code><a href="https://rdrr.io/r/utils/stack.html">unstack()</a></code></td>
<td align="left">Converts a stacked data frame into an unstacked data frame (or a list if the lengths of the samples are different)</td>
</tr>
<tr class="odd">
<td align="left"><code><a href="https://rdrr.io/r/stats/bartlett.test.html">bartlett.test()</a></code></td>
<td align="left">Perform Bartlett’s test for equality of variance</td>
</tr>
<tr class="even">
<td align="left"><code>leveneTest()</code></td>
<td align="left">Perform Levene’s test for equality of variance</td>
</tr>
</tbody>
</table></div>
</div>
<div id="data-and-hypotheses-1" class="section level3" number="5.4.2">
<h3>
<span class="header-section-number">5.4.2</span> Data and hypotheses<a class="anchor" aria-label="anchor" href="#data-and-hypotheses-1"><i class="fas fa-link"></i></a>
</h3>
<p>For example, suppose we now measure the body lengths of male guppies (in mm) collected from two rivers in Trinidad; the Aripo and the Guanapo. We want to test whether the mean body length differs between samples. We form the following null and alternative hypotheses:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: The mean body length does not differ between the two groups (<span class="math inline">\(\mu A = \mu G\)</span>)</li>
<li>
<span class="math inline">\(H_1\)</span>: The mean body length does differ between the two groups (<span class="math inline">\(\mu A \neq \mu G\)</span>)</li>
</ul>
<p>We use a two-sample, two-tailed t-test to see if we can reject the null hypothesis.</p>
<ul>
<li>We use a two-sample test because we now have two samples.</li>
<li>We use a two-tailed t-test because we want to know if our data suggest that the true (population) means are different from one another rather than that one mean is specifically bigger or smaller than the other.</li>
<li>We’re using Student’s t-test because the sample sizes are big and because we’re assuming that the parent populations have equal variance (We can check this later).</li>
</ul>
<p>The data are stored in stacked format in the file <code>data/raw/CS1-twosample.csv</code>.</p>
<p>Read this into R:</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">rivers</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/raw/CS1-twosample.csv"</span><span class="op">)</span></code></pre></div>
</div>
<div id="cs1-students-sumvisual" class="section level3" number="5.4.3">
<h3>
<span class="header-section-number">5.4.3</span> Summarise and visualise<a class="anchor" aria-label="anchor" href="#cs1-students-sumvisual"><i class="fas fa-link"></i></a>
</h3>
<p>Let’s summarise the data…</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">river</span>, data <span class="op">=</span> <span class="va">rivers</span>, <span class="va">summary</span><span class="op">)</span></code></pre></div>
<pre><code>##     river length.Min. length.1st Qu. length.Median length.Mean length.3rd Qu.
## 1   Aripo    17.50000       19.10000      20.10000    20.33077       21.30000
## 2 Guanapo    11.20000       17.50000      18.80000    18.29655       19.70000
##   length.Max.
## 1    26.40000
## 2    23.30000</code></pre>
<p>and visualise it:</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">river</span>, data <span class="op">=</span> <span class="va">rivers</span>,
        main <span class="op">=</span> <span class="st">"Male guppies"</span>,
        ylab <span class="op">=</span> <span class="st">"Length (mm)"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/cs1-twosample-rivers-boxplot-1.png" width="672"></div>
<p>The boxplot does appear to suggest that the two samples have different means, and moreover that the guppies in Guanapo may be smaller than the guppies in Aripo. It isn’t immediately obvious that the two populations don’t have equal variances though, so we plough on.</p>
</div>
<div id="implement-test" class="section level3" number="5.4.4">
<h3>
<span class="header-section-number">5.4.4</span> Implement test<a class="anchor" aria-label="anchor" href="#implement-test"><i class="fas fa-link"></i></a>
</h3>
<p>Perform a two-sample, two-tailed, t-test:</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">river</span>, data <span class="op">=</span> <span class="va">rivers</span>,
       alternative <span class="op">=</span> <span class="st">"two.sided"</span>,
       var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p>In this case, with the data in stacked format:</p>
<ul>
<li>The first argument must be in the formula format: <code>variables ~ category</code>
</li>
<li>The second argument must be the name of the data frame</li>
<li>The third argument gives the type of alternative hypothesis and must be one of <code>two.sided</code>, <code>greater</code> or <code>less</code>
</li>
<li>The fourth argument says whether the variance of the two samples can be assumed to be equal (Student’s t-test) or unequal (Welch’s t-test)</li>
</ul>
<p>This next section shows you that we can perform exactly the same test with the data in a different (unstacked) format. This is potentially somewhat redundant (or thorough depending on your point of view). Probably best just to do it anyway just in case you gain extra insight through repetition (it works for rowers…)</p>
<p>Convert the data to unstacked format and repeat the t test:</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create a new object that contains the unstacked data</span>
<span class="va">uns_rivers</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/stack.html">unstack</a></span><span class="op">(</span><span class="va">rivers</span><span class="op">)</span>

<span class="co"># have a look at the data</span>
<span class="va">uns_rivers</span></code></pre></div>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># perform the t-test</span>
<span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">uns_rivers</span><span class="op">$</span><span class="va">Guanapo</span>, <span class="va">uns_rivers</span><span class="op">$</span><span class="va">Aripo</span>,
       alternative <span class="op">=</span> <span class="st">"two.sided"</span>,
       var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
</div>
<div id="interpret-output-and-report-results" class="section level3" number="5.4.5">
<h3>
<span class="header-section-number">5.4.5</span> Interpret output and report results<a class="anchor" aria-label="anchor" href="#interpret-output-and-report-results"><i class="fas fa-link"></i></a>
</h3>
<p>Let’s look at the results of the t-test that we performed on the original (stacked) data frame:</p>
<pre><code>## 
##  Two Sample t-test
## 
## data:  length by river
## t = 3.8433, df = 66, p-value = 0.0002754
## alternative hypothesis: true difference in means between group Aripo and group Guanapo is not equal to 0
## 95 percent confidence interval:
##  0.9774482 3.0909868
## sample estimates:
##   mean in group Aripo mean in group Guanapo 
##              20.33077              18.29655</code></pre>
<ul>
<li>The 1st line gives the name of the test and the 2nd line reminds you what the dataset was called, and what variables were used.</li>
<li>The 3rd line contains the three key outputs from the test:
<ul>
<li>The calculated t-value is 3.8433 (we need this for reporting)</li>
<li>There are 66 degrees of freedom (we need this for reporting)</li>
<li>The p-value is 0.0002754.</li>
</ul>
</li>
<li>The 4th line simply states the alternative hypothesis in terms of the difference between the two sample means (testing if the two sample means are different is equivalent to testing whether the difference in the means is equal to zero).</li>
<li>The 5th and 6th lines give the 95th confidence interval (we don’t need to know this here).</li>
<li>The 7th, 8th and 9th lines give the sample means for each group (20.33077 in Aripo and 18.29655 in Guanapo) which we found earlier.</li>
</ul>
<p>Again, the p-value on the 3rd line is what we’re most interested in. Since the p-value is very small (much smaller than the standard significance level) we choose to say “that it is very unlikely that these two samples came from the same parent distribution and as such we can reject our null hypothesis” and state that:</p>
<blockquote>
<p>A Student’s t-test indicated that the mean body length of male guppies in the Guanapo river (18.29 mm) differs significantly from the mean body length of male guppies in the Aripo river (20.33 mm) (t = 3.8433, df = 66, p = 0.0003).</p>
</blockquote>
<p>Now there’s a conversation starter.</p>
</div>
<div id="assumptions-2" class="section level3" number="5.4.6">
<h3>
<span class="header-section-number">5.4.6</span> Assumptions<a class="anchor" aria-label="anchor" href="#assumptions-2"><i class="fas fa-link"></i></a>
</h3>
<p>In order to use a Student’s t-test (and for the results to be strictly valid) we have to make three assumptions:</p>
<ol style="list-style-type: decimal">
<li>The parent distributions from which the samples are taken are both normally distributed (which would lead to the sample data being normally distributed too).</li>
<li>Each data point in the samples is independent of the others.</li>
<li>The parent distributions should have the same variance.</li>
</ol>
<p>In this example the first assumption can be ignored as the sample sizes are large enough (because of maths, with Aripo containing 2 and Guanapo 2 samples). If the samples were smaller then we would use the tests from the previous section.</p>
<p>The second point we can do nothing about unless we know how the data were collected, so again we ignore it.</p>
<p>The third point regarding equality of variance can be tested using either Bartlett’s test (if the samples are normally distributed) or Levene’s test (if the samples are not normally distributed).
This is where it gets a bit trickier. Although we don’t care if the samples are normally distributed for the t-test to be valid (because the sample size is big enough to compensate), we do need to know if they are normally distributed in order to decide which variance test to use.</p>
<p>So we perform a <a href="cs1-one-sample-tests.html#shapiro-wilk-test">Shapiro-Wilk test</a> on both samples separately:</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">uns_rivers</span><span class="op">$</span><span class="va">Aripo</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  uns_rivers$Aripo
## W = 0.93596, p-value = 0.02802</code></pre>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">uns_rivers</span><span class="op">$</span><span class="va">Guanapo</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  uns_rivers$Guanapo
## W = 0.94938, p-value = 0.1764</code></pre>
<p>We can see that whilst the Guanapo data is probably normally distributed (p = 0.1764 &gt; 0.05), the Aripo data is unlikely to be normally distributed (p = 0.02802 &lt; 0.05). Remember that the p-value gives the probability of observing each sample if the parent population is actually normally distributed.
The Shapiro-Wilk test is quite sensitive to sample size. This means that if you have a large sample then even small deviations from normality will cause the sample to fail the test, whereas smaller samples are allowed to pass with much larger deviations. Here the Aripo data has nearly 40 points in it compared with the Guanapo data and so it is much easier for the Aripo sample to fail compared with the Guanapo data.</p>
</div>
<div id="exercise-2" class="section level3" number="5.4.7">
<h3>
<span class="header-section-number">5.4.7</span> Exercise<a class="anchor" aria-label="anchor" href="#exercise-2"><i class="fas fa-link"></i></a>
</h3>
<div class="exercise">
<p><span id="exr:unlabeled-div-3" class="exercise"><strong>Exercise 5.1  </strong></span>Q-Q plots for <code>rivers</code> data</p>
<p>Create the Q-Q plots for the two samples and discuss with your neighbour what you see in light of the results from the above Shapiro-Wilk test.</p>
<details><summary>
Answer
</summary><div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">uns_rivers</span><span class="op">$</span><span class="va">Aripo</span>, main <span class="op">=</span> <span class="st">"Aripo"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">uns_rivers</span><span class="op">$</span><span class="va">Aripo</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">uns_rivers</span><span class="op">$</span><span class="va">Guanapo</span>, main <span class="op">=</span> <span class="st">"Guanapo"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">uns_rivers</span><span class="op">$</span><span class="va">Guanapo</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/cs1-twosample-qqplot-1.png" width="672"></div>
<p>The Q-Q plots mirror what we found with the Shapiro-Wilk tests: the data for Aripo are pretty normally distributed, whereas the assumption of normality for the Guanapo data is less certain.</p>
</details>
</div>
<p><br></p>
<div class="highlight">
<p>Remember that statistical tests do not provide answers, they merely suggest patterns. Human interpretation is still a crucial aspect to what we do.</p>
</div>
<p>Nevertheless, the Shapiro-Wilk test has shown that the data are not normal <em>enough</em> and so in order to test for equality of variance we will use Levene’s test.
Levene’s test is not included in the default R packages and may require the installation of an additional package called <code>car</code> (Companion to Applied Regression).</p>
<p>To install the <code>car</code> package, run the following command in your console:</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"car"</span><span class="op">)</span></code></pre></div>
<p>Alternatively, go to <kbd>Tools</kbd> &gt; <kbd>Install packages…</kbd> &gt; <kbd>Packages</kbd>, type in <code>car</code> and press <kbd>Install</kbd></p>
<p>We can now perform Levene’s test:</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">leveneTest</span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">river</span>, data <span class="op">=</span> <span class="va">rivers</span><span class="op">)</span></code></pre></div>
<pre><code>## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  1.7732 0.1876
##       66</code></pre>
<p>Ignore any warning you might get about coercion to factors (the test needs to create grouped variables to work and R versions from 4.x onwards do not read in the data as factors).</p>
<p>The key bit of information is the 3rd line under the text <code>Pr(&gt;F)</code>. This is the p-value (0.1876) for this test. And this tells us the probability of observing these two samples if they come from distributions with the same variance. As this probability is greater than our arbitrary significance level of 0.05 then we can be somewhat confident that the necessary assumptions for carrying out Student’s t-test on these two samples was valid. (Once again woohoo!)</p>
<div class="note">
<p><strong>For information only:</strong></p>
<p>If we had wanted to carry out Bartlett’s test (i.e. if the data had been sufficiently normally distributed) then the command would have been:</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/bartlett.test.html">bartlett.test</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">river</span>, data <span class="op">=</span> <span class="va">rivers</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  length by river
## Bartlett's K-squared = 4.4734, df = 1, p-value = 0.03443</code></pre>
<p>The relevant p-value is given on the 3rd line.</p>
</div>
</div>
<div id="exercise-3" class="section level3" number="5.4.8">
<h3>
<span class="header-section-number">5.4.8</span> Exercise<a class="anchor" aria-label="anchor" href="#exercise-3"><i class="fas fa-link"></i></a>
</h3>
<div class="exercise">
<p><span id="exr:unlabeled-div-4" class="exercise"><strong>Exercise 5.2  </strong></span>Serum cholesterol concentrations in turtles</p>
<p>Using the following data, test the null hypothesis that male and female turtles have the same mean serum cholesterol concentrations.</p>
<div class="inline-table"><table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:cs1-twosample-turtle-data">Table 5.1: </span>Serum cholesterol (mg/100 ml
</caption>
<thead><tr>
<th style="text-align:right;background-color: white !important;">
Male
</th>
<th style="text-align:right;background-color: white !important;">
Female
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;background-color: white !important;">
220.1
</td>
<td style="text-align:right;background-color: white !important;">
223.4
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
218.6
</td>
<td style="text-align:right;background-color: white !important;">
221.5
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
229.6
</td>
<td style="text-align:right;background-color: white !important;">
230.2
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
228.8
</td>
<td style="text-align:right;background-color: white !important;">
224.3
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
222.0
</td>
<td style="text-align:right;background-color: white !important;">
223.8
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
224.1
</td>
<td style="text-align:right;background-color: white !important;">
230.8
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
226.5
</td>
<td style="text-align:right;background-color: white !important;">
NA
</td>
</tr>
</tbody>
</table></div>
<ol style="list-style-type: decimal">
<li>Write down the null and alternative hypotheses</li>
<li>Choose a representation for the data (stacked or unstacked) and create a <code>csv</code> file</li>
<li>Import the data into R</li>
<li>Summarise and visualise the data</li>
<li>Check your assumptions (normality and variance) using appropriate tests and plots</li>
<li>Perform a two-sample t-test</li>
<li>Write down a sentence that summarises the results that you have found</li>
</ol>
<details><summary>
Answer
</summary><p><strong>1. Hypotheses</strong></p>
<p><span class="math inline">\(H_0\)</span> : male mean <span class="math inline">\(=\)</span> female mean</p>
<p><span class="math inline">\(H_1\)</span> : male mean <span class="math inline">\(\neq\)</span> female mean</p>
<p><strong>2-4. Import Data, Summarise and visualise</strong></p>
<p>I’d always recommend storing data in tidy, stacked format (in fact I can’t think of any situation where I would want to store data in an untidy, unstacked format!) So for this example I manually input the data into Excel in the following layout, saving the data as a CSV file and reading it in:</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">turtle</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/examples/cs1-turtle.csv"</span><span class="op">)</span>

<span class="va">turtle</span></code></pre></div>
<pre><code>##    serum    sex
## 1  220.1   Male
## 2  218.6   Male
## 3  229.6   Male
## 4  228.8   Male
## 5  222.0   Male
## 6  224.1   Male
## 7  226.5   Male
## 8  223.4 Female
## 9  221.5 Female
## 10 230.2 Female
## 11 224.3 Female
## 12 223.8 Female
## 13 230.8 Female</code></pre>
<p>Let’s summarise the data…</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">serum</span> <span class="op">~</span> <span class="va">sex</span> , data <span class="op">=</span> <span class="va">turtle</span>, <span class="va">summary</span><span class="op">)</span></code></pre></div>
<pre><code>##      sex serum.Min. serum.1st Qu. serum.Median serum.Mean serum.3rd Qu.
## 1 Female   221.5000      223.5000     224.0500   225.6667      228.7250
## 2   Male   218.6000      221.0500     224.1000   224.2429      227.6500
##   serum.Max.
## 1   230.8000
## 2   229.6000</code></pre>
<p>and visualise the data:</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">serum</span> <span class="op">~</span> <span class="va">sex</span> , data <span class="op">=</span> <span class="va">turtle</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/cs1-twosample-turtle-boxplot-1.png" width="672"></div>
<p>As always we use the plot and summary to assess three things:</p>
<ol style="list-style-type: decimal">
<li>Does it look like we’ve loaded the data in correctly?
<ul>
<li>We have two groups and the extreme values of our plots seem to match with our dataset, so I’m happy that we haven’t done anything massively wrong here.</li>
</ul>
</li>
<li>Do we think that there is a difference between the two groups?
<ul>
<li>We need the result of the formal test to make sense given the data, so it’s important to develop a sense of what we think is going to happen here. Whilst the ranges of the two groups suggests that the Female serum levels might be higher than the males when we look at things more closely we realise that isn’t the case. The boxplot shows that the median values of the two groups is virtually identical and this is backed up by the summary statistics we calculated: the medians are both about 224.1, and the means are fairly close too (225.7 vs 224.2). Based on this, and the fact that there are only 13 observations in total I would be very surprised if any test came back showing that there was a difference between the groups.</li>
</ul>
</li>
<li>What do we think about assumptions?
<ul>
<li>Normality looks a bit worrying: whilst the Male group appears nice and symmetric (and so might be normal), the Female group appears to be quite skewed (since the median is much closer to the bottom than the top). We’ll have to look carefully at the more formal checks to decided whether we think the data are normal enough for us to use a t-test.</li>
<li>Homogeneity of variance. At this stage the spread of the data within each group looks similar, but because of the potential skew in the Female group we’ll again want to check the assumptions carefully.</li>
</ul>
</li>
</ol>
<p><strong>5. Check Assumptions</strong></p>
<p><strong>Normality</strong></p>
<p>Let’s look at the normality of each of the groups separately. There are several ways of getting at the <code>serum</code> values for Males and Females separately. We’ll use the unstacking method, then use Shapiro-Wilk followed by qqplots.</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">uns_turtle</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/stack.html">unstack</a></span><span class="op">(</span><span class="va">turtle</span>, <span class="va">serum</span> <span class="op">~</span> <span class="va">sex</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">uns_turtle</span><span class="op">$</span><span class="va">Male</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  uns_turtle$Male
## W = 0.94392, p-value = 0.6743</code></pre>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">uns_turtle</span><span class="op">$</span><span class="va">Female</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  uns_turtle$Female
## W = 0.84178, p-value = 0.1349</code></pre>
<p>The p-values for both Shapiro-Wilk tests are non-significant which suggests that the data are normal enough. This is a bit surprising given what we saw in the boxplot but there are two bits of information that we can use to reassure us.</p>
<ol style="list-style-type: decimal">
<li>The p-value for the Female group is smaller than for the Male group (suggesting that the Female group is closer to being non-normal than the Male group) which makes sense.</li>
<li>The Shapiro-Wilk test is generally quite relaxed about normality for small sample sizes (and notoriously strict for very large sample sizes). For a group with only 6 data points in it, the data would actually have to have a really, really skewed distribution. Given that the Female group only has 6 data points in it, it’s not too surprising that the Shapiro-Wilk test came back saying everything is OK.</li>
</ol>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">uns_turtle</span><span class="op">$</span><span class="va">Male</span>, main <span class="op">=</span> <span class="st">"Male"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">uns_turtle</span><span class="op">$</span><span class="va">Male</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">uns_turtle</span><span class="op">$</span><span class="va">Female</span>, main <span class="op">=</span> <span class="st">"Female"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">uns_turtle</span><span class="op">$</span><span class="va">Female</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/cs1-twosample-turtle-qqplot-1.png" width="672"></div>
<p>The results from the Q-Q plots echo what we’ve already seen from the Shapiro-Wilk analyses. The Male group doesn’t look too bad whereas the Female group looks somewhat dodgy.</p>
<p>Overall, the assumption of normality of the data doesn’t appear to be very well met at all, but we do have to bear in mind that there are only a few data points in each group and we might just be seeing this pattern in the data due to random chance rather than because the underlying populations are actually not normally distributed. Personally, though I’d edge towards non-normal here.</p>
<p><strong>Homogeneity of Variance</strong></p>
<p>It’s not clear whether the data are normal or not, so it isn’t clear which test to use here. The sensible approach is to do both and hope that they agree (fingers crossed!)</p>
<p>Bartlett’s test gives us:</p>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/bartlett.test.html">bartlett.test</a></span><span class="op">(</span><span class="va">serum</span> <span class="op">~</span> <span class="va">sex</span>, <span class="va">turtle</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  serum by sex
## Bartlett's K-squared = 0.045377, df = 1, p-value = 0.8313</code></pre>
<p>and Levene’s test gives us:</p>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># load if needed</span>
<span class="co"># library(car)</span>

<span class="fu">leveneTest</span><span class="op">(</span><span class="va">serum</span> <span class="op">~</span> <span class="va">sex</span>, <span class="va">turtle</span><span class="op">)</span></code></pre></div>
<pre><code>## Levene's Test for Homogeneity of Variance (center = median)
##       Df F value Pr(&gt;F)
## group  1  0.2434 0.6315
##       11</code></pre>
<p>The good news is that both Levene and Bartlett agree that there is homogeneity of variance between the two groups (thank goodness!).</p>
<p>Overall, what this means is that we’re not too sure about normality, but that homogeneity of variance is pretty good.</p>
<p><strong>6. Carry out a two-sample t-test</strong></p>
<p>Because of the result of the Bartlett test I know that I can carry out a two-sample Student’s t-test (as opposed to a two-sample Welch’s t-test, if you’re confused, see Figure <a href="cs1-two-sample.html#fig:fig-cs1-diagram-which-test">5.2</a>)</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">serum</span> <span class="op">~</span> <span class="va">sex</span> , <span class="va">turtle</span>,
       alternative<span class="op">=</span><span class="st">"two.sided"</span>,
       var.equal<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  serum by sex
## t = 0.62681, df = 11, p-value = 0.5436
## alternative hypothesis: true difference in means between group Female and group Male is not equal to 0
## 95 percent confidence interval:
##  -3.575759  6.423378
## sample estimates:
## mean in group Female   mean in group Male 
##             225.6667             224.2429</code></pre>
<p>With a p-value of 0.544, this test tells me that there is insufficient evidence to suggest that the means of the two groups are different. A suitable summary sentence would be:</p>
<blockquote>
<p>A Student’s two-sample t-test indicated that the mean serum cholesterol level did not differ significantly between Male and Female turtles (t = 0.627, df = 11, p = 0.544).</p>
</blockquote>
<p><strong>Discussion</strong></p>
<p>In reality, because of the ambiguous normality assumption assessment, for this dataset I would actually carry out two different tests; the two-sample t-test with equal variance and the Mann-Whitney U test. If both of them agreed then it wouldn’t matter too much which one I reported (I’d personally report both with a short sentence to say that I’m doing that because it wasn’t clear whether the assumption of normality had or had not been met), but it would be acceptable to report just one.</p>
</details>
</div>
</div>
</div>
<div id="cs1-mannwhitney-u-test" class="section level2" number="5.5">
<h2>
<span class="header-section-number">5.5</span> Mann-Whitney U test<a class="anchor" aria-label="anchor" href="#cs1-mannwhitney-u-test"><i class="fas fa-link"></i></a>
</h2>
<p>This test also compares two samples, however for this test (in contrast to Student’s t-test) we don’t have to assume that the parent distributions are normally distributed. In order to compare the medians of the two groups we do still need the parent distributions (and consequently the samples) to both have the same shape and variance. In this test we look to see if the medians of the two parent distributions differ significantly from each other.</p>
<div id="section-commands-3" class="section level3" number="5.5.1">
<h3>
<span class="header-section-number">5.5.1</span> Section commands<a class="anchor" aria-label="anchor" href="#section-commands-3"><i class="fas fa-link"></i></a>
</h3>
<p>No new commands used in this section.</p>
</div>
<div id="data-and-hypotheses-2" class="section level3" number="5.5.2">
<h3>
<span class="header-section-number">5.5.2</span> Data and hypotheses<a class="anchor" aria-label="anchor" href="#data-and-hypotheses-2"><i class="fas fa-link"></i></a>
</h3>
<p>Again, we use the <code>rivers</code> dataset. We want to test whether the median body length of male guppies differs between samples. We form the following null and alternative hypotheses:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: The difference in median body length between the two groups is 0 (<span class="math inline">\(\mu A - \mu G = 0\)</span>)</li>
<li>H1: The difference in median body length between the two groups is not 0 (<span class="math inline">\(\mu A - \mu G \neq 0\)</span>)</li>
</ul>
<p>We use a two-tailed Mann-Whitney U test to see if we can reject the null hypothesis.</p>
</div>
<div id="summarise-and-visualise-2" class="section level3" number="5.5.3">
<h3>
<span class="header-section-number">5.5.3</span> Summarise and visualise<a class="anchor" aria-label="anchor" href="#summarise-and-visualise-2"><i class="fas fa-link"></i></a>
</h3>
<p>We did this in the <a href="cs1-two-sample.html#cs1-students-sumvisual">previous section</a>.</p>
</div>
<div id="implement-test-1" class="section level3" number="5.5.4">
<h3>
<span class="header-section-number">5.5.4</span> Implement test<a class="anchor" aria-label="anchor" href="#implement-test-1"><i class="fas fa-link"></i></a>
</h3>
<p>Perform a two-tailed, Mann-Whitney U test:</p>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">river</span>, data <span class="op">=</span> <span class="va">rivers</span>,
            alternative <span class="op">=</span> <span class="st">"two.sided"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  length by river
## W = 841, p-value = 0.0006464
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>In this case, with the data in a tidy format:</p>
<ul>
<li>The first argument must be in the formula format: <code>variable ~ category</code>
</li>
<li>The second argument must be the name of the data frame</li>
<li>The third argument gives the type of alternative hypothesis and must be one of <code>two.sided</code>, <code>greater</code> or <code>less</code>
</li>
</ul>
</div>
<div id="interpret-output-and-report-results-1" class="section level3" number="5.5.5">
<h3>
<span class="header-section-number">5.5.5</span> Interpret output and report results<a class="anchor" aria-label="anchor" href="#interpret-output-and-report-results-1"><i class="fas fa-link"></i></a>
</h3>
<p>You may get a warning message in the console stating <code>cannot compute exact p-value with ties</code>. This just means that some of the data points have exactly the same value which affects the internal mathematics slightly. However, given that the p-value is so very small, this is not something that we need to worry about.</p>
<p>After the warning message:</p>
<ul>
<li>The 1st line gives the name of the test and the 2nd line reminds you what the dataset was called, and what variables were used</li>
<li>The 3rd line contains the two key outputs from the test:
<ul>
<li>The calculated W-value is 841 (we’ll use this in reporting)</li>
<li>The p-value is 0.0006464.</li>
</ul>
</li>
<li>The 4th line simply states the alternative hypothesis in terms of the difference between the two sample medians in that if there were a difference then one distribution would be shifted relative to the other.</li>
</ul>
<p>Given that the p-value is less than 0.05 we can reject the null hypothesis at this confidence level.
Again, the p-value on the 3rd line is what we’re most interested in. Since the p-value is very small (much smaller than the standard significance level) we choose to say “that it is very unlikely that these two samples came from the same parent distribution and as such we can reject our null hypothesis.”</p>
<p>To put it more completely, we can state that:</p>
<blockquote>
<p>A Mann-Whitney test indicated that the median body length of male guppies in the Guanapo river (18.8 mm) differs significantly from the median body length of male guppies in the Aripo river (20.1 mm) (W = 841, p = 0.0006).</p>
</blockquote>
</div>
<div id="assumptions-3" class="section level3" number="5.5.6">
<h3>
<span class="header-section-number">5.5.6</span> Assumptions<a class="anchor" aria-label="anchor" href="#assumptions-3"><i class="fas fa-link"></i></a>
</h3>
<p>We have checked these previously.</p>
</div>
<div id="exercise-4" class="section level3" number="5.5.7">
<h3>
<span class="header-section-number">5.5.7</span> Exercise<a class="anchor" aria-label="anchor" href="#exercise-4"><i class="fas fa-link"></i></a>
</h3>
<div class="exercise">
<p><span id="exr:unlabeled-div-5" class="exercise"><strong>Exercise 5.3  </strong></span>Analyse the turtle dataset from before using a Mann Whitney test.</p>
<p>We follow the same process as with Student’s t-test.</p>
<details><summary>
Answer
</summary><p><strong>Hypotheses</strong></p>
<p><span class="math inline">\(H_0\)</span> : male median <span class="math inline">\(=\)</span> female median</p>
<p><span class="math inline">\(H_1\)</span> : male median <span class="math inline">\(\neq\)</span> female median</p>
<p><strong>Summarise and visualise</strong></p>
<p>This is the same as before.</p>
<p><strong>Assumptions</strong></p>
<p>We’ve already checked that the variances of the two groups are similar, so we’re OK there. Whilst the Mann-Whitney test doesn’t require normality or symmetry of distributions it does require that the distributions have the same shape. In this example, with just a handful of data points in each group, it’s quite hard to make this call one way or another. My advice in this case would be say that unless it’s obvious that the distributions are very different we can just allow this assumption to pass, and you’re only going see obvious differences in distribution shape when you have considerably more data points than we have here.</p>
<p><strong>Carry out a Mann-Whitney test</strong></p>
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test</a></span><span class="op">(</span><span class="va">serum</span> <span class="op">~</span> <span class="va">sex</span>, data <span class="op">=</span> <span class="va">turtle</span>,
            alternative <span class="op">=</span> <span class="st">"two.sided"</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon rank sum exact test
## 
## data:  serum by sex
## W = 26, p-value = 0.5338
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>This gives us exactly the same conclusion that we got from the two-sample t-test <em>i.e</em>. that there isn’t any significant difference between the two groups.</p>
<p>A Mann-Whitney test indicated that there wasn’t a significant difference in the median Serum Cholesterol levels between male and female turtles (W = 26, p = 0.534)</p>
</details>
</div>
</div>
</div>
<div id="cs1-paired-two-sample-t-test" class="section level2" number="5.6">
<h2>
<span class="header-section-number">5.6</span> Paired two-sample t-test<a class="anchor" aria-label="anchor" href="#cs1-paired-two-sample-t-test"><i class="fas fa-link"></i></a>
</h2>
<p>A paired t-test is used when we have two samples of continuous data that can be paired (examples of these sort of data would be weights of individuals before and after a diet). This test is applicable if the number of paired points within the samples is large (&gt;30) or, if the number of points is small, then this test also works when the parent distributions are normally distributed.</p>
<div id="section-commands-4" class="section level3" number="5.6.1">
<h3>
<span class="header-section-number">5.6.1</span> Section commands<a class="anchor" aria-label="anchor" href="#section-commands-4"><i class="fas fa-link"></i></a>
</h3>
<p>There are no new commands in this section.</p>
</div>
<div id="data-and-hypotheses-3" class="section level3" number="5.6.2">
<h3>
<span class="header-section-number">5.6.2</span> Data and hypotheses<a class="anchor" aria-label="anchor" href="#data-and-hypotheses-3"><i class="fas fa-link"></i></a>
</h3>
<p>For example, suppose we measure the cortisol levels in 20 adult females (nmol/l) first thing in the morning and again in the evening. We want to test whether the cortisol levels differs between the two measurement times. We will initially form the following null and alternative hypotheses:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: There is no difference in cortisol level between times (<span class="math inline">\(\mu M = \mu E\)</span>)</li>
<li>
<span class="math inline">\(H_1\)</span>: There is a difference in cortisol levels between times (<span class="math inline">\(\mu M \neq \mu E\)</span>)</li>
</ul>
<p>We use a two-sample, two-tailed paired t-test to see if we can reject the null hypothesis.</p>
<ul>
<li>We use a <strong>two-sample</strong> test because we now have two samples</li>
<li>We use a <strong>two-tailed</strong> t-test because we want to know if our data suggest that the true (population) means are different from one another rather than that one mean is specifically bigger or smaller than the other</li>
<li>We use a <strong>paired</strong> test because each data point in the first sample can be linked to another data point in the second sample by a connecting factor</li>
<li>We’re using a <strong>t-test</strong> because we’re assuming that the parent populations are normal and have equal variance (We’ll check this in a bit)</li>
</ul>
<p>The data are stored in unstacked format in the file “CS1-twopaired.csv.”
Read this into R:</p>
<div class="sourceCode" id="cb66"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cortisol</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/raw/CS1-twopaired.csv"</span><span class="op">)</span></code></pre></div>
</div>
<div id="summarise-and-visualise-3" class="section level3" number="5.6.3">
<h3>
<span class="header-section-number">5.6.3</span> Summarise and visualise<a class="anchor" aria-label="anchor" href="#summarise-and-visualise-3"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">cortisol</span><span class="op">)</span></code></pre></div>
<pre><code>##     morning         evening     
##  Min.   :146.1   Min.   : 60.1  
##  1st Qu.:266.6   1st Qu.:137.8  
##  Median :320.5   Median :188.9  
##  Mean   :313.5   Mean   :197.4  
##  3rd Qu.:359.7   3rd Qu.:260.8  
##  Max.   :432.5   Max.   :379.3</code></pre>
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">cortisol</span>, ylab <span class="op">=</span> <span class="st">"Level (nmol/l)"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/cs1-pairedt-sumvisual-1.png" width="672"></div>
<p>The box plot does not capture how the cortisol level of each individual subject has changed though. We can explore the individual changes between morning and evening by creating a boxplot of the <em>differences</em> between the two times of measurement.</p>
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># calculate the difference between evening and morning values</span>
<span class="va">changeCor</span> <span class="op">&lt;-</span> <span class="va">cortisol</span><span class="op">$</span><span class="va">evening</span> <span class="op">-</span> <span class="va">cortisol</span><span class="op">$</span><span class="va">morning</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">changeCor</span>, ylab <span class="op">=</span> <span class="st">"Change in cortisol (nmol/l)"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/cs1-pairedt-diff-1.png" width="672"></div>
<p>The differences in cortisol levels appear to be very much less than zero, (meaning that the evening cortisol levels appear to be much lower than the morning ones). As such we would expect that the test would give a pretty significant result.</p>
</div>
<div id="implement-test-2" class="section level3" number="5.6.4">
<h3>
<span class="header-section-number">5.6.4</span> Implement test<a class="anchor" aria-label="anchor" href="#implement-test-2"><i class="fas fa-link"></i></a>
</h3>
<p>Perform a two-sample, two-tailed, paired t-test:</p>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">cortisol</span><span class="op">$</span><span class="va">evening</span>, <span class="va">cortisol</span><span class="op">$</span><span class="va">morning</span>,
       alternative <span class="op">=</span> <span class="st">"two.sided"</span>, paired <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<ul>
<li>The first two arguments must be vectors containing the numerical data for both samples</li>
<li>The third argument gives the type of alternative hypothesis and must be one of <code>two.sided</code>, <code>greater</code> or <code>less</code>
</li>
<li>The fourth argument says that the data are paired</li>
</ul>
</div>
<div id="interpret-output-and-report-results-2" class="section level3" number="5.6.5">
<h3>
<span class="header-section-number">5.6.5</span> Interpret output and report results<a class="anchor" aria-label="anchor" href="#interpret-output-and-report-results-2"><i class="fas fa-link"></i></a>
</h3>
<pre><code>## 
##  Paired t-test
## 
## data:  cortisol$evening and cortisol$morning
## t = -5.1833, df = 19, p-value = 5.288e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -162.96038  -69.20962
## sample estimates:
## mean of the differences 
##                -116.085</code></pre>
<p>From our perspective the value of interested is on the 3rd line (p-value = 5.288e10<sup>-5</sup>). Given that this is substantially less than 0.05 we can reject the null hypothesis and state:</p>
<blockquote>
<p>A two-tailed, paired t-test indicated that the cortisol level in adult females differed significantly between the morning (313.5 nmol/l) and the evening (197.4 nmol/l) (t = -5.1833, df = 19, p = 5.3x10<sup>-5</sup>).</p>
</blockquote>
</div>
<div id="assumptions-4" class="section level3" number="5.6.6">
<h3>
<span class="header-section-number">5.6.6</span> Assumptions<a class="anchor" aria-label="anchor" href="#assumptions-4"><i class="fas fa-link"></i></a>
</h3>
<p>You will do this in the exercise!</p>
</div>
<div id="exercise-5" class="section level3" number="5.6.7">
<h3>
<span class="header-section-number">5.6.7</span> Exercise<a class="anchor" aria-label="anchor" href="#exercise-5"><i class="fas fa-link"></i></a>
</h3>
<div class="exercise">
<p><span id="exr:unlabeled-div-6" class="exercise"><strong>Exercise 5.4  </strong></span>Checking assumptions</p>
<p>Check the assumptions necessary for this this paired t-test.
Was a paired t-test an appropriate test?</p>
<details><summary>
Answer
</summary><p>A paired test is really just a one-sample test in disguise. We actually don’t care too much about the distributions of the individual groups. Instead we care about the properties of the <strong>differences</strong>. So for a paired t-test to be valid for this dataset, we need the differences between the morning and evening values to be normally distributed.</p>
<p>Let’s check this with Shapiro-Wilk and Q-Q plots using the <code>changeCor</code> variable we created earlier.</p>
<div class="sourceCode" id="cb73"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">changeCor</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  changeCor
## W = 0.92362, p-value = 0.1164</code></pre>
<div class="sourceCode" id="cb75"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">changeCor</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">changeCor</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/unnamed-chunk-7-1.png" width="672"></div>
<p>The Shapiro-Wilk test says that the data are normal enough and whilst the Q-Q plot is mostly fine, there is some suggestion of snaking at the bottom left. I’m actually OK with this because the suggestion of snaking is actually only due to a single point (the last point on the left). If you cover that point up with your thumb (or finger of your choice) then the remaining points in the Q-Q plot look pretty damn good, and so the suggestion of snaking is actually driven by only a single point (which can happen by chance). As such I’m actually happy that the assumption of normality is well met in this case. This <strong>single point</strong> check is a useful thing to remember when assessing diagnostic plots.</p>
<p>So, yep, a paired t-test is appropriate for this dataset.</p>
</details>
</div>
</div>
</div>
<div id="cs1-twosample-wilcoxon-signed-rank" class="section level2" number="5.7">
<h2>
<span class="header-section-number">5.7</span> Wilcoxon signed-rank test<a class="anchor" aria-label="anchor" href="#cs1-twosample-wilcoxon-signed-rank"><i class="fas fa-link"></i></a>
</h2>
<p>A Wilcoxon signed-rank test is an alternative to a paired t-test. It does not require that the data are drawn from normal distributions, but it does require that the distribution of the differences is symmetric. We’re effectively testing to see if the median of the differences between the two samples differs significantly from zero.</p>
<div id="section-commands-5" class="section level3" number="5.7.1">
<h3>
<span class="header-section-number">5.7.1</span> Section commands<a class="anchor" aria-label="anchor" href="#section-commands-5"><i class="fas fa-link"></i></a>
</h3>
<p>There are no new commands in this section.</p>
</div>
<div id="data-and-hypotheses-4" class="section level3" number="5.7.2">
<h3>
<span class="header-section-number">5.7.2</span> Data and hypotheses<a class="anchor" aria-label="anchor" href="#data-and-hypotheses-4"><i class="fas fa-link"></i></a>
</h3>
<p>Using the <code>cortisol</code> dataset from before we form the following null and alternative hypotheses:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: The median of the difference in cortisol levels between the two groups is 0 (<span class="math inline">\(\mu M = \mu E\)</span>)</li>
<li>
<span class="math inline">\(H_1\)</span>: The median of the difference in cortisol levels between the two groups is not 0 (<span class="math inline">\(\mu M \neq \mu E\)</span>)</li>
</ul>
<p>We use a two-tailed Wilcoxon signed-rank test to see if we can reject the null hypothesis.</p>
</div>
<div id="summarise-and-visualise-4" class="section level3" number="5.7.3">
<h3>
<span class="header-section-number">5.7.3</span> Summarise and visualise<a class="anchor" aria-label="anchor" href="#summarise-and-visualise-4"><i class="fas fa-link"></i></a>
</h3>
<p>Already implemented previously.</p>
</div>
<div id="implement-test-3" class="section level3" number="5.7.4">
<h3>
<span class="header-section-number">5.7.4</span> Implement test<a class="anchor" aria-label="anchor" href="#implement-test-3"><i class="fas fa-link"></i></a>
</h3>
<p>Perform a two-tailed, Wilcoxon signed-rank test:</p>
<div class="sourceCode" id="cb76"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test</a></span><span class="op">(</span><span class="va">cortisol</span><span class="op">$</span><span class="va">morning</span>, <span class="va">cortisol</span><span class="op">$</span><span class="va">evening</span>,
            alternative <span class="op">=</span> <span class="st">"two.sided"</span>, paired <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<ul>
<li>The first two arguments must be the two samples in numerical vector format</li>
<li>The second argument gives the type of alternative hypothesis and must be one of <code>two.sided</code>, <code>greater</code> or <code>less</code>
</li>
<li>The third argument indicates that the test is paired</li>
</ul>
</div>
<div id="interpret-output-and-report-results-3" class="section level3" number="5.7.5">
<h3>
<span class="header-section-number">5.7.5</span> Interpret output and report results<a class="anchor" aria-label="anchor" href="#interpret-output-and-report-results-3"><i class="fas fa-link"></i></a>
</h3>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  cortisol$morning and cortisol$evening
## V = 197, p-value = 0.0001678
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>The p value is given on the 3rd line (p-value = 0.0001678). Given that this is less than 0.05 we can still reject the null hypothesis.</p>
<blockquote>
<p>A two-tailed, Wilcoxon signed-rank test indicated that the median cortisol level in adult females differed significantly between the morning (320.5 nmol/l) and the evening (188.9 nmol/l) (V = 197, p = 0.00017).</p>
</blockquote>
</div>
<div id="assumptions-5" class="section level3" number="5.7.6">
<h3>
<span class="header-section-number">5.7.6</span> Assumptions<a class="anchor" aria-label="anchor" href="#assumptions-5"><i class="fas fa-link"></i></a>
</h3>
</div>
<div id="exercise-6" class="section level3" number="5.7.7">
<h3>
<span class="header-section-number">5.7.7</span> Exercise<a class="anchor" aria-label="anchor" href="#exercise-6"><i class="fas fa-link"></i></a>
</h3>
<div class="exercise">
<p><span id="exr:unlabeled-div-7" class="exercise"><strong>Exercise 5.5  </strong></span>Deer legs</p>
<p>Using the following data, test the null hypothesis that the fore and hind legs of deer are the same length.</p>
<div class="inline-table"><table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:cs1-pairedwilcoxon-example">Table 5.2: </span>Deer leg length (cm)
</caption>
<thead><tr>
<th style="text-align:right;background-color: white !important;">
hindleg
</th>
<th style="text-align:right;background-color: white !important;">
foreleg
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;background-color: white !important;">
142
</td>
<td style="text-align:right;background-color: white !important;">
138
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
140
</td>
<td style="text-align:right;background-color: white !important;">
136
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
144
</td>
<td style="text-align:right;background-color: white !important;">
147
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
144
</td>
<td style="text-align:right;background-color: white !important;">
139
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
142
</td>
<td style="text-align:right;background-color: white !important;">
143
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
146
</td>
<td style="text-align:right;background-color: white !important;">
141
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
149
</td>
<td style="text-align:right;background-color: white !important;">
143
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
150
</td>
<td style="text-align:right;background-color: white !important;">
145
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
142
</td>
<td style="text-align:right;background-color: white !important;">
136
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
148
</td>
<td style="text-align:right;background-color: white !important;">
146
</td>
</tr>
</tbody>
</table></div>
<p>Do these results provide any evidence to suggest that fore- and hind-leg length differ in deer?</p>
<ol style="list-style-type: decimal">
<li>Write down the null and alternative hypotheses</li>
<li>Choose a representation for the data (stacked or unstacked) and create a csv file</li>
<li>Import the data into R</li>
<li>Summarise and visualise the data</li>
<li>Perform a two-sample paired t-test</li>
<li>Perform a Wilcoxon signed-rank test</li>
<li>Now check your assumptions (normality and variance) using appropriate tests</li>
<li>Discuss with your (virtual) neighbour which test is most appropriate?</li>
<li>Write down a sentence that summarise the results that you have found</li>
</ol>
<details><summary>
Answer
</summary><p><strong>1. Hypotheses</strong></p>
<p><span class="math inline">\(H_0\)</span> : foreleg average (mean or median) <span class="math inline">\(=\)</span> hindleg average (mean or median)</p>
<p><span class="math inline">\(H_1\)</span> : foreleg average <span class="math inline">\(\neq\)</span> hindleg average</p>
<p><strong>2-4. Import Data, Summarise and visualise</strong></p>
<p>I always recommend storing data in stacked format even in this example, even though in this case it might seem easier to store your data in unstacked format (this is pretty much the only time where this is even a sensible option). So for this example I manually input the data into excel in the following layout:</p>
<div class="sourceCode" id="cb78"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">deer</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/examples/cs1-deer.csv"</span><span class="op">)</span></code></pre></div>
<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead><tr>
<th style="text-align:right;background-color: white !important;">
id
</th>
<th style="text-align:left;background-color: white !important;">
leg
</th>
<th style="text-align:right;background-color: white !important;">
length
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;background-color: white !important;">
1
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
142
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
2
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
140
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
3
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
144
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
4
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
144
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
5
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
142
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
6
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
146
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
7
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
149
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
8
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
150
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
9
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
142
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
10
</td>
<td style="text-align:left;background-color: white !important;">
hindleg
</td>
<td style="text-align:right;background-color: white !important;">
148
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
1
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
138
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
2
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
136
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
3
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
147
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
4
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
139
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
5
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
143
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
6
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
141
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
7
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
143
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
8
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
145
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
9
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
136
</td>
</tr>
<tr>
<td style="text-align:right;background-color: white !important;">
10
</td>
<td style="text-align:left;background-color: white !important;">
foreleg
</td>
<td style="text-align:right;background-color: white !important;">
146
</td>
</tr>
</tbody>
</table>
<p>The ordering of the data is important here; the first hindleg row corresponds to the first foreleg row, the second to the second and so on. To indicate this we use an <code>id</code> column, where each observation has a unique ID.</p>
<p>Let’s look at the data and see what we can see.</p>
<div class="sourceCode" id="cb79"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/aggregate.html">aggregate</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">leg</span>, data <span class="op">=</span> <span class="va">deer</span>, <span class="va">summary</span><span class="op">)</span></code></pre></div>
<pre><code>##       leg length.Min. length.1st Qu. length.Median length.Mean length.3rd Qu.
## 1 foreleg      136.00         138.25        142.00      141.40         144.50
## 2 hindleg      140.00         142.00        144.00      144.70         147.50
##   length.Max.
## 1      147.00
## 2      150.00</code></pre>
<div class="sourceCode" id="cb81"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">leg</span>, data <span class="op">=</span> <span class="va">deer</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/unnamed-chunk-10-1.png" width="672"></div>
<p>It looks as though there might be a difference between the legs, with hindlegs being longer than forelegs. However, this representation obscures the fact that we have <em>paired</em> data. What we really need to look at is the difference in leg length for each deer:</p>
<div class="sourceCode" id="cb82"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">uns_deer</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/stack.html">unstack</a></span><span class="op">(</span><span class="va">deer</span>, <span class="va">length</span> <span class="op">~</span> <span class="va">leg</span><span class="op">)</span>
<span class="va">deerDiff</span> <span class="op">&lt;-</span> <span class="va">uns_deer</span><span class="op">$</span><span class="va">hindleg</span> <span class="op">-</span> <span class="va">uns_deer</span><span class="op">$</span><span class="va">foreleg</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">deerDiff</span><span class="op">)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    -3.0     2.5     4.5     3.3     5.0     6.0</code></pre>
<div class="sourceCode" id="cb84"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">deerDiff</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/unnamed-chunk-11-1.png" width="672"></div>
<p>This gives us a much clearer picture. It looks as though the hindlegs are about 4 cm longer than the forelegs, on average. It also suggests that our leg differences might not be normally distributed (the data look a bit skewed).</p>
<p><strong>5. Perform a two-sample t-test</strong></p>
<div class="sourceCode" id="cb85"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">leg</span>, data <span class="op">=</span> <span class="va">deer</span>, paired <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  length by leg
## t = -3.4138, df = 9, p-value = 0.007703
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.486752 -1.113248
## sample estimates:
## mean of the differences 
##                    -3.3</code></pre>
<p>The paired t-test here assumes that the data is stored exactly as we have entered it (i.e. that the first hindleg row matches the first foreleg row). Here we apparently see a significant difference.</p>
<p><strong>6. Perform a paired Wilcoxon test</strong></p>
<div class="sourceCode" id="cb87"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/wilcox.test.html">wilcox.test</a></span><span class="op">(</span><span class="va">length</span> <span class="op">~</span> <span class="va">leg</span>, data <span class="op">=</span> <span class="va">deer</span>, paired <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning in wilcox.test.default(x = c(138L, 136L, 147L, 139L, 143L, 141L, :
## cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Wilcoxon signed rank test with continuity correction
## 
## data:  length by leg
## V = 4, p-value = 0.01859
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>The paired Wilcoxon test makes the same assumptions about the order of the data as the paired t-test. Here again we have a significant difference.</p>
<p><strong>7. Check assumptions</strong></p>
<p>We need to consider the distribution of the <em>difference</em> in leg lengths rather than the individual distributions.</p>
<div class="sourceCode" id="cb90"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">deerDiff</span><span class="op">)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  deerDiff
## W = 0.81366, p-value = 0.02123</code></pre>
<div class="sourceCode" id="cb92"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqnorm</a></span><span class="op">(</span><span class="va">deerDiff</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/qqnorm.html">qqline</a></span><span class="op">(</span><span class="va">deerDiff</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs1-practical-two_sample_files/figure-html/unnamed-chunk-14-1.png" width="672"></div>
<p>Both our Shapiro-Wilk test and our Q-Q plot suggest that the difference data aren’t normally distributed, which rules out a paired t-test. We should therefore consider a paired Wilcoxon test next. Remember that this test requires that the distribution of differences be symmetric, whereas our box-plot from before suggested that the data were very much skewed.</p>
<p><strong>8. Conclusions</strong></p>
<p>So, frustratingly, neither of our tests are appropriate for this dataset. The differences in fore- and hind leg lengths are neither normal enough for a paired t-test nor are they symmetric enough for a Wilcoxon test and we don’t have enough data to just use the t-test (we’d need more than 30 points or so). So what do we do in this situation? Well the answer is that there aren’t actually any traditional statistical tests that are valid for this dataset as it stands!</p>
<p>There are two options available to someone:</p>
<ol style="list-style-type: decimal">
<li>try transforming the raw data (take logs, square root, reciprocals) and hope that one of them leads to a modified dataset that satisfies the assumptions of one of the tests we’ve covered, or</li>
<li>use a permutation test approach (which would work but is beyond the scope of this course).</li>
</ol>
<p>The reason I included this example in the first practical is purely to illustrate how a very simple dataset with an apparently clear message (leg lengths differ within deer) can be intractable. You don’t need to have very complex datasets before you go beyond the capabilities of classical statistics.</p>
</details>
</div>
<p>As Jeremy Clarkson <a href="https://www.quotes.net/mquote/941330">would put it</a>:</p>
<blockquote>
<p>And on that bombshell, it’s time to end. Goodnight!</p>
</blockquote>
</div>
</div>
<div id="key-points-1" class="section level2" number="5.8">
<h2>
<span class="header-section-number">5.8</span> Key points<a class="anchor" aria-label="anchor" href="#key-points-1"><i class="fas fa-link"></i></a>
</h2>
<div class="keypoints">
<ul>
<li>We use two-sample tests to see if two samples of continuous data come from the same parent distribution</li>
<li>This essentially boils down to testing if the mean or median differs between the two samples</li>
<li>There are 5 key two-sample tests: Student’s t-test, Welch’s t-test, Mann-Whitney U test, paired t-test and Wilcoxon signed-rank test</li>
<li>Which one you use depends on normality of the distribution, sample size, paired or unpaired data and variance of the samples</li>
<li>Parametric tests are used if the data are normally distributed or the sample size is large</li>
<li>Non-parametric tests are used if the data are not normally distributed <em>and</em> the sample size is small</li>
<li>Equality of variance then determines which test is appropriate</li>
<li>You <a href="cs1-two-sample.html#two-sample-choosing-a-test">can ask yourself</a> 3 questions to determine the test:
<ol style="list-style-type: decimal">
<li>is my data paired?</li>
<li>do I need a parametric or non-parametric test</li>
<li>can I assume equality of variance?</li>
</ol>
</li>
</ul>
</div>

</div>
</div>



  <div class="chapter-nav">
<div class="prev"><a href="cs1-one-sample-tests.html"><span class="header-section-number">4</span> One-sample tests</a></div>
<div class="next"><a href="cs2-intro.html"><span class="header-section-number">6</span> Introduction</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#cs1-two-sample"><span class="header-section-number">5</span> Two-sample tests</a></li>
<li><a class="nav-link" href="#objectives-2"><span class="header-section-number">5.1</span> Objectives</a></li>
<li><a class="nav-link" href="#purpose-and-aim-1"><span class="header-section-number">5.2</span> Purpose and aim</a></li>
<li>
<a class="nav-link" href="#two-sample-choosing-a-test"><span class="header-section-number">5.3</span> Choosing a test</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#data-format"><span class="header-section-number">5.3.1</span> Data format</a></li></ul>
</li>
<li>
<a class="nav-link" href="#cs1-students-t-test"><span class="header-section-number">5.4</span> Student’s t-test</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#section-commands-2"><span class="header-section-number">5.4.1</span> Section commands</a></li>
<li><a class="nav-link" href="#data-and-hypotheses-1"><span class="header-section-number">5.4.2</span> Data and hypotheses</a></li>
<li><a class="nav-link" href="#cs1-students-sumvisual"><span class="header-section-number">5.4.3</span> Summarise and visualise</a></li>
<li><a class="nav-link" href="#implement-test"><span class="header-section-number">5.4.4</span> Implement test</a></li>
<li><a class="nav-link" href="#interpret-output-and-report-results"><span class="header-section-number">5.4.5</span> Interpret output and report results</a></li>
<li><a class="nav-link" href="#assumptions-2"><span class="header-section-number">5.4.6</span> Assumptions</a></li>
<li><a class="nav-link" href="#exercise-2"><span class="header-section-number">5.4.7</span> Exercise</a></li>
<li><a class="nav-link" href="#exercise-3"><span class="header-section-number">5.4.8</span> Exercise</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#cs1-mannwhitney-u-test"><span class="header-section-number">5.5</span> Mann-Whitney U test</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#section-commands-3"><span class="header-section-number">5.5.1</span> Section commands</a></li>
<li><a class="nav-link" href="#data-and-hypotheses-2"><span class="header-section-number">5.5.2</span> Data and hypotheses</a></li>
<li><a class="nav-link" href="#summarise-and-visualise-2"><span class="header-section-number">5.5.3</span> Summarise and visualise</a></li>
<li><a class="nav-link" href="#implement-test-1"><span class="header-section-number">5.5.4</span> Implement test</a></li>
<li><a class="nav-link" href="#interpret-output-and-report-results-1"><span class="header-section-number">5.5.5</span> Interpret output and report results</a></li>
<li><a class="nav-link" href="#assumptions-3"><span class="header-section-number">5.5.6</span> Assumptions</a></li>
<li><a class="nav-link" href="#exercise-4"><span class="header-section-number">5.5.7</span> Exercise</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#cs1-paired-two-sample-t-test"><span class="header-section-number">5.6</span> Paired two-sample t-test</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#section-commands-4"><span class="header-section-number">5.6.1</span> Section commands</a></li>
<li><a class="nav-link" href="#data-and-hypotheses-3"><span class="header-section-number">5.6.2</span> Data and hypotheses</a></li>
<li><a class="nav-link" href="#summarise-and-visualise-3"><span class="header-section-number">5.6.3</span> Summarise and visualise</a></li>
<li><a class="nav-link" href="#implement-test-2"><span class="header-section-number">5.6.4</span> Implement test</a></li>
<li><a class="nav-link" href="#interpret-output-and-report-results-2"><span class="header-section-number">5.6.5</span> Interpret output and report results</a></li>
<li><a class="nav-link" href="#assumptions-4"><span class="header-section-number">5.6.6</span> Assumptions</a></li>
<li><a class="nav-link" href="#exercise-5"><span class="header-section-number">5.6.7</span> Exercise</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#cs1-twosample-wilcoxon-signed-rank"><span class="header-section-number">5.7</span> Wilcoxon signed-rank test</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#section-commands-5"><span class="header-section-number">5.7.1</span> Section commands</a></li>
<li><a class="nav-link" href="#data-and-hypotheses-4"><span class="header-section-number">5.7.2</span> Data and hypotheses</a></li>
<li><a class="nav-link" href="#summarise-and-visualise-4"><span class="header-section-number">5.7.3</span> Summarise and visualise</a></li>
<li><a class="nav-link" href="#implement-test-3"><span class="header-section-number">5.7.4</span> Implement test</a></li>
<li><a class="nav-link" href="#interpret-output-and-report-results-3"><span class="header-section-number">5.7.5</span> Interpret output and report results</a></li>
<li><a class="nav-link" href="#assumptions-5"><span class="header-section-number">5.7.6</span> Assumptions</a></li>
<li><a class="nav-link" href="#exercise-6"><span class="header-section-number">5.7.7</span> Exercise</a></li>
</ul>
</li>
<li><a class="nav-link" href="#key-points-1"><span class="header-section-number">5.8</span> Key points</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/cambiotraining/corestats_in_r/blob/master/cs1-practical-two_sample.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/cambiotraining/corestats_in_r/edit/master/cs1-practical-two_sample.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Core Statistics in R</strong>" was written by Matt Castle and Martin van Rongen. It was last built on 2021-10-19.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
