<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" class="no-js">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Chapter 23 Linear regression with grouped data | Core Statistics in R</title>
<meta name="author" content="Matt Castle and Martin van Rongen">
<meta name="description" content="23.1 Objectives  Questions How do I perform a linear regression on grouped data? Objectives Be able to perform a linear regression on grouped data in R Calculate the linear regression for...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 23 Linear regression with grouped data | Core Statistics in R">
<meta property="og:type" content="book">
<meta property="og:description" content="23.1 Objectives  Questions How do I perform a linear regression on grouped data? Objectives Be able to perform a linear regression on grouped data in R Calculate the linear regression for...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 23 Linear regression with grouped data | Core Statistics in R">
<meta name="twitter:description" content="23.1 Objectives  Questions How do I perform a linear regression on grouped data? Objectives Be able to perform a linear regression on grouped data in R Calculate the linear regression for...">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references --><link rel="shortcut icon" href="favicon.ico">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<!-- CSS : implied media="all" --><link rel="stylesheet" href="stylesheets/full-stylesheet.css">
<link rel="stylesheet" href="stylesheets/styleguide.css">
<link rel="stylesheet" href="stylesheets/style.css">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.5.3/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.5.3/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.4/tabs.js"></script><script src="libs/bs3compat-0.2.4/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><script type="text/javascript" src="//use.typekit.com/hyb5bko.js"></script><script type="text/javascript">try{Typekit.load();}catch(e){}</script><script type="text/javascript">  document.documentElement.className += " js";</script>
</head>
<body class="campl-theme-2" data-spy="scroll" data-target="#toc">

<!--[if lt IE 7]>
<div class="lt-ie9 lt-ie8 lt-ie7">
<![endif]-->
<!--[if IE 7]>
<div class="lt-ie9 lt-ie8">
<![endif]-->
<!--[if IE 8]>
<div class="lt-ie9">
<![endif]-->

	<a href="#primary-nav" class="campl-skipTo">skip to primary navigation</a>
	<a href="#content" class="campl-skipTo">skip to content</a>
	<div class="campl-row campl-global-header">
		<div class="campl-wrap clearfix">
			<div class="campl-header-container campl-column8" id="global-header-controls">
				<a href="http://www.cam.ac.uk" class="campl-main-logo">
					<img alt="University of Cambridge" src="images/interface/main-logo-small.png" height="38px;"></a>

				<ul class="campl-unstyled-list campl-horizontal-navigation campl-global-navigation clearfix">
<li>
						<a href="#study-with-us">Study at Cambridge</a>
					</li>
					<li>
						<a href="#about-the-university">About the University</a>
					</li>
					<li>
						<a href="http://www.cam.ac.uk/research" class="campl-no-drawer">Research at Cambridge</a>
					</li>
				</ul>
</div>

			<div class="campl-column2">
				<div class="campl-quicklinks">
				</div>
			</div>

			<div class="campl-column2">

				<div class="campl-site-search" id="site-search-btn">

					<label for="header-search" class="hidden">Search site</label>
					<div class="campl-search-input">
						<form action="http://search.cam.ac.uk/web" method="get">
						<input id="header-search" type="text" name="query" value="" placeholder="Search"><input type="image" class="campl-search-submit " src="images/interface/btn-search-header.png">
</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="campl-row campl-global-header campl-search-drawer">
		<div class="campl-wrap clearfix">
			<form class="campl-site-search-form" id="site-search-container" action="">
				<div class="campl-search-form-wrapper clearfix">
					<input type="text" class="text" placeholder="Search"><input type="image" class="campl-search-submit" src="images/interface/btn-search.png">
</div>
			</form>
		</div>
	</div>

	<div class="campl-row campl-global-navigation-drawer">

		<div class="campl-wrap clearfix">
			<div class="campl-column12 campl-home-link-container">
				<a href="">Home</a>
			</div>
		</div>
		<div class="campl-wrap clearfix">
			<div class="campl-column12 campl-global-navigation-mobile-list campl-global-navigation-list">
				<div class="campl-global-navigation-outer clearfix" id="study-with-us">
					<ul class="campl-unstyled-list campl-global-navigation-header-container ">
<li><a href="http://www.cam.ac.uk/study-at-cambridge">Study at Cambridge</a></li>
					</ul>
<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list campl-global-navigation-secondary-with-children">
<li>
								<a href="http://www.study.cam.ac.uk/undergraduate/">Undergraduate</a>
								<ul class="campl-global-navigation-tertiary campl-unstyled-list">
<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/courses">Courses</a>
									</li>
									<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/applying">Applying</a>
									</li>
									<li>
										<a href="http://www.undergraduate.study.cam.ac.uk/events">Events and open days</a>
									</li>
								  <li>
										<a href="http://www.undergraduate.study.cam.ac.uk/finance">Fees and finance</a>
									</li>
								  <li>
										<a href="http://www.becambridge.com/">Student blogs and videos</a>
									</li>
								</ul>
</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list campl-global-navigation-secondary-with-children">
<li>
								<a href="http://www.graduate.study.cam.ac.uk/">Graduate</a>
								<ul class="campl-global-navigation-tertiary campl-unstyled-list">
<li>
										<a href="http://www.graduate.study.cam.ac.uk/why-cambridge/welcome-vice-chancellor">Why Cambridge</a>
									</li>
									<li>
										<a href="http://www.graduate.study.cam.ac.uk/courses%0A">Course directory</a>
									</li>
									<li>
									<a href="http://www.graduate.study.cam.ac.uk/how-do-i-apply">How to apply</a>
</li>
									<li><a href="http://www.cambridgestudents.cam.ac.uk/fees-and-funding">Fees and funding</a></li>
									<li><a href="http://www.graduate.study.cam.ac.uk/faqs/applicant">Frequently asked questions</a></li>
								</ul>
</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list last">
<li>
								<a href="http://www.internationalstudents.cam.ac.uk">International students</a>
							</li>
							<li>
								<a href="http://www.ice.cam.ac.uk">Continuing education</a>
							</li>
							<li>
								<a href="http://www.epe.admin.cam.ac.uk/">Executive and professional education</a>
							</li>
							<li>
								<a href="http://www.educ.cam.ac.uk">Courses in education</a>
							</li>
						</ul>
</div>
				</div>

				<div class="campl-global-navigation-outer clearfix" id="about-the-university">
					<ul class="campl-global-navigation-header-container campl-unstyled-list">
<li><a href="http://www.cam.ac.uk/about-the-university">About the University</a></li>
					</ul>
<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.cam.ac.uk/about-the-university/how-the-university-and-colleges-work">How the University and Colleges work</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/history">History</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/visiting-the-university">Visiting the University</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/term-dates-and-calendars">Term dates and calendars</a>
							</li>
							<li class="last">
								<a href="http://map.cam.ac.uk">Map</a>
							</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.communications.cam.ac.uk/">For media</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/video-and-audio">Video and audio</a>
							</li>
							<li>
								<a href="http://webservices.admin.cam.ac.uk/fae/">Find an expert</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-the-university/publications">Publications</a>
							</li>
							<li class="last">
								<a href="http://www.cam.ac.uk/global-cambridge">Global Cambridge</a>
							</li>
						</ul>
</div>
					<div class="campl-column4">
						<ul class="campl-global-navigation-container campl-unstyled-list">
<li>
								<a href="http://www.cam.ac.uk/news">News</a>
							</li>
							<li>
								<a href="http://www.admin.cam.ac.uk/whatson/">Events</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/public-engagement">Public engagement</a>
							</li>
							<li>
								<a href="http://www.jobs.cam.ac.uk">Jobs</a>
							</li>
							<li class="last">
								<a href="https://www.philanthropy.cam.ac.uk/">Give to Cambridge</a>
							</li>
						</ul>
</div>
				</div>

				<div class="campl-global-navigation-outer clearfix" id="our-research">
					<ul class="campl-global-navigation-header-container campl-unstyled-list">
<li><a href="">Research at Cambridge</a></li>
					</ul>
</div>
			</div>

			<ul class="campl-unstyled-list campl-quicklinks-list campl-global-navigation-container ">
<li>
					<a href="http://www.cam.ac.uk/for-staff">For staff</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/current-students">For current students</a>
				</li>
				<li>
					<a href="http://www.alumni.cam.ac.uk">For alumni</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/for-business">For business</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/colleges-and-departments">Colleges &amp; departments</a>
				</li>
				<li>
					<a href="http://www.lib.cam.ac.uk/libraries/">Libraries &amp; facilities</a>
				</li>
				<li>
					<a href="http://www.cam.ac.uk/museums-and-collections">Museums &amp; collections</a>
				</li>
				<li class="last">
					<a href="http://www.cam.ac.uk/email-and-phone-search">Email &amp; phone search</a>
				</li>
			</ul>
</div>
	</div>
    <!-- .campl-global-header ends -->

	<div class="campl-row campl-page-header campl-sub-section-page">
		<div class="campl-wrap clearfix">
			<div class="campl-column12">
				<div class="campl-content-container">
					<div class="campl-breadcrumb" id="breadcrumb">
						<ul class="campl-unstyled-list campl-horizontal-navigation clearfix">
<li class="first-child">
								<a href="https://bioinfotraining.bio.cam.ac.uk/" class="campl-home ir">Home</a>
							</li>
							<li>
								<a href="">Courses</a>
							</li>
							<li>
								<a href="">Training Materials</a>
							</li>
							<li>
								<a href="index.html">Core Statistics in R
							</a>
</li>
						</ul>
</div>
					<!--<p class="campl-page-title">Bioinformatics Training Materials</p>-->

					<p class="campl-mobile-parent"><a href=""><span class="campl-back-btn campl-menu-indicator"></span>Studying at Cambridge</a></p>
				</div>
			</div>
		</div>
	</div>

	<div class="campl-row campl-page-header">
		<div class="campl-wrap clearfix campl-local-navigation" id="local-nav">
			<div class="campl-local-navigation-container">
				<ul class="campl-unstyled-list">
<li><a href="https://training.cam.ac.uk/bioinformatics/search">Course schedule</a></li>
					<li>
<a href="#" class="campl-selected">Additional information</a>
						<ul class="campl-unstyled-list local-dropdown-menu">
<li><a href="#">Additional resources</a></li>
							<li><a href="https://bioinfotraining.bio.cam.ac.uk/about/findus">Where to find us?</a></li>
							<li><a href="#">Frequently asked questions</a></li>
						</ul>
</li>
					<li><a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate">Further training</a></li>
				</ul>
</div>
		</div>



		<div class="campl-wrap clearfix campl-page-sub-title campl-recessed-sub-title">
			<div class="campl-column12">
				<div class="campl-content-container">
					<p class="campl-sub-title">Core Statistics in R</p>
				</div>
			</div>
		</div>
	</div>


		<div class="campl-row campl-content campl-recessed-content">
			<div class="campl-wrap clearfix">
				<div class="campl-column9  campl-main-content" id="content">
					<div class="campl-content-container">
						<div>
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <br><button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Overview</a></li>
<li class="book-part">CoreStats 1: Simple hypothesis testing</li>
<li><a class="" href="cs1-intro.html"><span class="header-section-number">2</span> Introduction</a></li>
<li class="book-part">CoreStats 1 (Practicals)</li>
<li><a class="" href="introduction.html"><span class="header-section-number">3</span> Introduction</a></li>
<li><a class="" href="cs1-one-sample-tests.html"><span class="header-section-number">4</span> One-sample tests</a></li>
<li><a class="" href="cs1-one-sample-t-test.html"><span class="header-section-number">5</span> One-sample t-test</a></li>
<li><a class="" href="cs1-onesample-wilcoxon-signed-rank.html"><span class="header-section-number">6</span> Wilcoxon signed-rank test</a></li>
<li><a class="" href="cs1-two-sample.html"><span class="header-section-number">7</span> Two-sample tests</a></li>
<li><a class="" href="cs1-students-t-test.html"><span class="header-section-number">8</span> Student’s t-test</a></li>
<li><a class="" href="cs1-mannwhitney-u-test.html"><span class="header-section-number">9</span> Mann-Whitney U test</a></li>
<li><a class="" href="cs1-paired-two-sample-t-test.html"><span class="header-section-number">10</span> Paired two-sample t-test</a></li>
<li><a class="" href="cs1-twosample-wilcoxon-signed-rank.html"><span class="header-section-number">11</span> Wilcoxon signed-rank test</a></li>
<li class="book-part">CoreStats 2: Categorical predictors</li>
<li><a class="" href="cs2-intro.html"><span class="header-section-number">12</span> Introduction</a></li>
<li class="book-part">CoreStats 2 (Practicals)</li>
<li><a class="" href="introduction-1.html"><span class="header-section-number">13</span> Introduction</a></li>
<li><a class="" href="cs2-anova.html"><span class="header-section-number">14</span> ANOVA</a></li>
<li><a class="" href="kruskal-wallis-test.html"><span class="header-section-number">15</span> Kruskal-Wallis test</a></li>
<li class="book-part">CoreStats 3: Continuous predictors</li>
<li><a class="" href="cs3-intro.html"><span class="header-section-number">16</span> Introduction</a></li>
<li class="book-part">CoreStats 3 (Practicals)</li>
<li><a class="" href="introduction-2.html"><span class="header-section-number">17</span> Introduction</a></li>
<li><a class="" href="correlation-coefficients.html"><span class="header-section-number">18</span> Correlation coefficients</a></li>
<li><a class="" href="linear-regression.html"><span class="header-section-number">19</span> Linear regression</a></li>
<li class="book-part">CoreStats 4: Two predictor variables</li>
<li><a class="" href="cs4-intro.html"><span class="header-section-number">20</span> Introduction</a></li>
<li class="book-part">CoreStats 4 (Practicals)</li>
<li><a class="" href="introduction-3.html"><span class="header-section-number">21</span> Introduction</a></li>
<li><a class="" href="two-way-anova.html"><span class="header-section-number">22</span> Two-way ANOVA</a></li>
<li><a class="active" href="linear-regression-with-grouped-data.html"><span class="header-section-number">23</span> Linear regression with grouped data</a></li>
<li class="book-part">CoreStats 5: Multiple predictor variables</li>
<li><a class="" href="cs5-intro.html"><span class="header-section-number">24</span> Introduction</a></li>
<li class="book-part">CoreStats 5 (Practicals)</li>
<li><a class="" href="introduction-4.html"><span class="header-section-number">25</span> Introduction</a></li>
<li><a class="" href="linear-models.html"><span class="header-section-number">26</span> Linear models</a></li>
<li><a class="" href="model-comparisons.html"><span class="header-section-number">27</span> Model comparisons</a></li>
<li class="book-part">CoreStats 6: Power analysis</li>
<li><a class="" href="cs6-intro.html"><span class="header-section-number">28</span> Introduction</a></li>
<li class="book-part">CoreStats 6 (Practicals)</li>
<li><a class="" href="introduction-5.html"><span class="header-section-number">29</span> Introduction</a></li>
<li><a class="" href="power-analysis.html"><span class="header-section-number">30</span> Power analysis</a></li>
<li><a class="" href="statistical-reporting.html"><span class="header-section-number">31</span> Statistical reporting</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="linear-regression-with-grouped-data" class="section level1" number="23">
<h1>
<span class="header-section-number">23</span> Linear regression with grouped data<a class="anchor" aria-label="anchor" href="#linear-regression-with-grouped-data"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-11" class="section level2" number="23.1">
<h2>
<span class="header-section-number">23.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-11"><i class="fas fa-link"></i></a>
</h2>
<div class="objectives">
<p><strong>Questions</strong></p>
<ul>
<li>How do I perform a linear regression on grouped data?</li>
</ul>
<p><strong>Objectives</strong></p>
<ul>
<li>Be able to perform a linear regression on grouped data in R</li>
<li>Calculate the linear regression for individual groups and visualise these with the data</li>
<li>Understand and be able to create equations of the line of best fit</li>
<li>Be able to deal with interactions in this context</li>
</ul>
</div>
</div>
<div id="purpose-and-aim-7" class="section level2" number="23.2">
<h2>
<span class="header-section-number">23.2</span> Purpose and aim<a class="anchor" aria-label="anchor" href="#purpose-and-aim-7"><i class="fas fa-link"></i></a>
</h2>
<p>A linear regression analysis with grouped data is used when we have one categorical predictor variable (or factor), and one continuous predictor variable. The response variable must still be continuous however.</p>
<p>For example in an experiment that looks at light intensity in woodland, how is light intensity (continuous: lux) affected by the height at which the measurement is taken, recorded as depth measured from the top of the canopy (continuous: metres) and by the type of woodland (categorical: Conifer or Broad leaf).</p>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-2-1.png" width="672"></div>
<p>When analysing this type of data we want to know:</p>
<ol style="list-style-type: decimal">
<li>Is there a difference between the groups?</li>
<li>Does the continuous predictor variable affect the continuous response variable (does canopy depth affect measured light intensity?)</li>
<li>Is there any interaction between the two predictor variables? Here an interaction would display itself as a difference in the slopes of the lines of best fit for each group, so for example perhaps the conifer dataset has a significantly steeper line than the broad leaf woodland dataset.</li>
</ol>
<p>In this case, no interaction means that the lines of best fit will have the same slope.
Essentially the analysis is identical to two-way ANOVA (and R doesn’t really notice the difference).</p>
<ol style="list-style-type: decimal">
<li>We will plot the data and visually inspect it.</li>
<li>We will test for an interaction and if it doesn’t exist then:
<ol style="list-style-type: lower-alpha">
<li>We can test to see if either predictor variable has an effect (i.e. do the lines of best fit have different intercepts? and is the common gradient significantly different from zero?)</li>
</ol>
</li>
</ol>
<p>We will first consider how to visualise the data before then carrying out an appropriate statistical test.</p>
</div>
<div id="section-commands-11" class="section level2" number="23.3">
<h2>
<span class="header-section-number">23.3</span> Section commands<a class="anchor" aria-label="anchor" href="#section-commands-11"><i class="fas fa-link"></i></a>
</h2>
<p>New commands used in this section:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">Function</th>
<th align="left">Description</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left"><code><a href="https://rdrr.io/r/base/subset.html">subset()</a></code></td>
<td align="left">Creates a subset of the data</td>
</tr></tbody>
</table></div>
</div>
<div id="data-and-hypotheses-10" class="section level2" number="23.4">
<h2>
<span class="header-section-number">23.4</span> Data and hypotheses<a class="anchor" aria-label="anchor" href="#data-and-hypotheses-10"><i class="fas fa-link"></i></a>
</h2>
<p>The data are stored in <code>data/raw/CS4-treelight.csv</code>.</p>
<p>Read in the data and inspect it:</p>
<div class="sourceCode" id="cb230"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># read in the data</span>
<span class="va">treelight</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/raw/CS4-treelight.csv"</span><span class="op">)</span>

<span class="co"># inspect the data</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">treelight</span><span class="op">)</span></code></pre></div>
<pre><code>##      Light Depth Species
## 1 4105.646  1.00 Conifer
## 2 4933.925  1.75 Conifer
## 3 4416.527  2.50 Conifer
## 4 4528.618  3.25 Conifer
## 5 3442.610  4.00 Conifer
## 6 4640.297  4.75 Conifer</code></pre>
<p><code>treelight</code> is a data frame with three variables; <code>Light</code>, <code>Depth</code> and <code>Species</code>. <code>Light</code> is the continuous response variable, <code>Depth</code> is the continuous predictor variable and <code>Species</code> is the categorical predictor variables.</p>
</div>
<div id="summarise-and-visualise-10" class="section level2" number="23.5">
<h2>
<span class="header-section-number">23.5</span> Summarise and visualise<a class="anchor" aria-label="anchor" href="#summarise-and-visualise-10"><i class="fas fa-link"></i></a>
</h2>
<div class="sourceCode" id="cb232"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
     data <span class="op">=</span> <span class="va">treelight</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-4-1.png" width="672"></div>
<p>This plots all of the points in the data set on the same window, but unfortunately there isn’t a way of easily distinguishing them, at least not using base R. We will need to extract the correct subset data from the <code>treelight</code> dataframe.</p>
<p>Create subsets of the data frame and look at the raw data:</p>
<div class="sourceCode" id="cb233"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># subset the conifers</span>
<span class="va">conLight</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">treelight</span>,
                   subset <span class="op">=</span> <span class="op">(</span><span class="va">Species</span> <span class="op">==</span> <span class="st">"Conifer"</span><span class="op">)</span><span class="op">)</span>

<span class="co"># subset the broad leaf</span>
<span class="va">broLight</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">treelight</span>,
                   subset <span class="op">=</span> <span class="op">(</span><span class="va">Species</span> <span class="op">==</span> <span class="st">"Broadleaf"</span><span class="op">)</span><span class="op">)</span>

<span class="co"># look at the first few rows of the raw data</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">conLight</span><span class="op">)</span></code></pre></div>
<pre><code>##      Light Depth Species
## 1 4105.646  1.00 Conifer
## 2 4933.925  1.75 Conifer
## 3 4416.527  2.50 Conifer
## 4 4528.618  3.25 Conifer
## 5 3442.610  4.00 Conifer
## 6 4640.297  4.75 Conifer</code></pre>
<div class="sourceCode" id="cb235"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">broLight</span><span class="op">)</span></code></pre></div>
<pre><code>##    Light Depth   Species
## 14  7652 2.438 Broadleaf
## 15  6866 3.488 Broadleaf
## 16  5437 8.316 Broadleaf
## 17  7327 1.597 Broadleaf
## 18  5991 6.265 Broadleaf
## 19  7574 2.651 Broadleaf</code></pre>
<p>The <code>subset</code> function creates subsets of data frames. The first argument is the original data frame, and the subset argument is a logical expression that defines which observations (rows) should be extracted. The logical expression must be enclosed in parentheses. In the first case it says (<code>Species == "Conifer"</code>). This tells R to only extract the rows of the original data frame which have <code>Conifer</code> in the species variable column. Ditto for <code>Broadleaf</code>.
We can use these smaller data frames to distinguish between the points in the plot.</p>
<p>Before we do that, we need to calculate the linear regression for each group, and add them to the plot:</p>
<p>Type this in:</p>
<div class="sourceCode" id="cb237"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># linear regression for Broadleaf</span>
<span class="va">lm.Broadleaf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
                   data <span class="op">=</span> <span class="va">broLight</span><span class="op">)</span>

<span class="co"># linear regression for Conifer</span>
<span class="va">lm.Conifer</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
                 data <span class="op">=</span> <span class="va">conLight</span><span class="op">)</span></code></pre></div>
<p>Now type this in to create the plot with the data and the linear regressions:</p>
<div class="sourceCode" id="cb238"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create a new plot based on Light ~ Depth</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>, 
     data <span class="op">=</span> <span class="va">treelight</span>, type <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span>

<span class="co"># add the Broadleaf data</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
     data <span class="op">=</span> <span class="va">broLight</span>, col <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span>

<span class="co"># add the Conifer data</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
     data <span class="op">=</span> <span class="va">conLight</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span>

<span class="co"># add the Broadleaf linear regression</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">lm.Broadleaf</span>, col <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span>

<span class="co"># add the Conifer linear regression</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">lm.Conifer</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-7-1.png" width="672"></div>
<p>You should now have a basic plot that looks similar to the figure above (but with different labels, no legend and different characters).</p>
<p>(Optional) Modify your graph to make it look the same as the above figure.</p>
<p>Looking at this plot, there doesn’t appear to be any significant interaction between the woodland type (<code>Broadleaf</code> and <code>Conifer</code>) and the depth at which light measurements were taken (<code>Depth</code>) on the amount of light intensity getting through the canopy as the gradients of the two lines appear to be very similar. There does appear to be a noticeable slope to both lines and both lines look as though they have very different intercepts. All of this suggests that there isn’t any interaction but that both <code>Depth</code> and <code>Species</code> have a significant effect on <code>Light</code> independently.</p>
</div>
<div id="implement-the-test-5" class="section level2" number="23.6">
<h2>
<span class="header-section-number">23.6</span> Implement the test<a class="anchor" aria-label="anchor" href="#implement-the-test-5"><i class="fas fa-link"></i></a>
</h2>
<p>In this case we’re going to implement the test before checking the assumptions (I know, let’s live a little!). You’ll find out why soon…</p>
<p>We can test for a possible interaction more formally:</p>
<div class="sourceCode" id="cb239"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span> <span class="op">*</span> <span class="va">Species</span>,
         data <span class="op">=</span> <span class="va">treelight</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Remember that <code>Depth * Species</code> is a shorthand way of writing the full set of <code>Depth + Species + Depth:Species</code> terms in R <em>i.e.</em> both main effects and the interaction effect.</p>
</div>
<div id="interpret-output-and-present-results-1" class="section level2" number="23.7">
<h2>
<span class="header-section-number">23.7</span> Interpret output and present results<a class="anchor" aria-label="anchor" href="#interpret-output-and-present-results-1"><i class="fas fa-link"></i></a>
</h2>
<p>This gives the following output:</p>
<pre><code>## Analysis of Variance Table
## 
## Response: Light
##               Df   Sum Sq  Mean Sq  F value    Pr(&gt;F)    
## Depth          1 30812910 30812910 107.8154 2.861e-09 ***
## Species        1 51029543 51029543 178.5541 4.128e-11 ***
## Depth:Species  1   218138   218138   0.7633    0.3932    
## Residuals     19  5430069   285793                       
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>As with two-way ANOVA we have a row in the table for each of the different effects that we’ve asked R to consider. The last column is the important one as this contains the p-values. We need to look at the interaction row first.
<code>Depth:Species</code> has a p-value of 0.393 (which is bigger than 0.05) and so we can conclude that the interaction between <code>Depth</code> and <code>Species</code> isn’t significant. As such we can now consider whether each of the predictor variables independently has an effect. Both <code>Depth</code> and <code>Species</code> have very small p-values (2.86x10<sup>-9</sup> and 4.13x10 <sup>-11</sup>) and so we can conclude that they do have a significant effect on <code>Light</code>.</p>
<p>This means that the two lines of best fit should have the same non-zero slope, but different intercepts. We would now like to know what those values are.</p>
<div id="finding-intercept-values" class="section level3" number="23.7.1">
<h3>
<span class="header-section-number">23.7.1</span> Finding intercept values<a class="anchor" aria-label="anchor" href="#finding-intercept-values"><i class="fas fa-link"></i></a>
</h3>
<p>Unfortunately, R doesn’t make this obvious and easy for us and there is some deciphering required getting this right.
For a simple straight line such as the linear regression for the conifer dataset by itself, the output is relatively straightforward.</p>
<div class="sourceCode" id="cb241"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
   data <span class="op">=</span> <span class="va">conLight</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Light ~ Depth, data = conLight)
## 
## Coefficients:
## (Intercept)        Depth  
##      5014.0       -292.2</code></pre>
<p>And we can interpret this as meaning that the intercept of the line of best fit is 5014 and the coefficient of the depth variable (the number in front of it in the equation) is -292.2.</p>
<p>So, the equation of the line of best fit is given by:</p>
<p><span class="math display">\[\begin{equation}
Light = 5014 + -292.2 * Depth
\end{equation}\]</span></p>
<p>This came from fitting a simple linear model using the conifer dataset, and has the meaning that for every extra 1 m of depth of forest canopy we lose 292.2 lux of light.</p>
<p>When we looked at the full dataset, we found that interaction wasn’t important. This means that we will have a model with two distinct intercepts but only a single slope (that’s what you get for a linear regression without any interaction), so we need to ask R to calculate that specific combination. The command for that is simply:</p>
<div class="sourceCode" id="cb243"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span> <span class="op">+</span> <span class="va">Species</span>,
   data <span class="op">=</span> <span class="va">treelight</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Light ~ Depth + Species, data = treelight)
## 
## Coefficients:
##    (Intercept)           Depth  SpeciesConifer  
##         7962.0          -262.2         -3113.0</code></pre>
<p>Notice the <code><a href="https://rdrr.io/r/base/Arithmetic.html">+</a></code> symbol in the argument, as opposed to the <code><a href="https://rdrr.io/r/base/Arithmetic.html">*</a></code> symbol used earlier. This means that we are explicitly <em>not</em> including an interaction term in this fit, and consequently we are forcing R to calculate the equation of lines which have the same gradient.</p>
<p>Ideally we would like R to give us two equations, one for each forest type, so four parameters in total.
Unfortunately, R is parsimonious and doesn’t do that. Instead R gives you three coefficients, and these require a bit of interpretation.</p>
<p>The first two numbers that R returns (underneath <code>Intercept</code> and <code>Depth</code>) are the exact intercept and slope coefficients for one of the lines (in this case they correspond to the data for <code>Broadleaf</code> woodlands).</p>
<p>For the coefficients belonging to the other line, R uses these first two coefficients as baseline values and expresses the other coefficients relative to these ones. R also doesn’t tell you explicitly which group it is using as its baseline reference group! (Did I mention that R can be very helpful at times 😉?)</p>
<p>So, how to decipher the above output?</p>
<p>First, I need to work out which group has been used as the baseline.
* It will be the group that comes first alphabetically, so it should be <code>Broadleaf</code>
* The other way to check would be to look and see which group is not mentioned in the above table. <code>Conifer</code> is mentioned (in the <code>SpeciesConifer</code> heading) and so again the baseline group is <code>Broadleaf.</code>
This means that the intercept value and <code>Depth</code> coefficient correspond to the <code>Broadleaf</code> group and as a result I know what the equation of one of my lines is:</p>
<p>Broadleaf:</p>
<p><span class="math display">\[\begin{equation}
Light = 7962 + -262.2 * Depth
\end{equation}\]</span></p>
<p>In this example we know that the gradient is the same for both lines (because we explicitly asked R not to include an interaction), so all I need to do is find the intercept value for the <code>Conifer</code> group. Unfortunately, the final value given underneath <code>SpeciesConifer</code> does not give me the intercept for <code>Conifer</code>, instead it tells me the difference between the <code>Conifer</code> group intercept and the baseline intercept i.e. the equation for the line of best fit for conifer woodland is given by:</p>
<p><span class="math display">\[\begin{equation}
Light = (7962 + -3113) + -262.2 * Depth
\end{equation}\]</span></p>
<p><span class="math display">\[\begin{equation}
Light = 4829 + -262.2 * Depth
\end{equation}\]</span></p>
</div>
<div id="adding-multiple-regression-lines" class="section level3" number="23.7.2">
<h3>
<span class="header-section-number">23.7.2</span> Adding multiple regression lines<a class="anchor" aria-label="anchor" href="#adding-multiple-regression-lines"><i class="fas fa-link"></i></a>
</h3>
<p>Unfortunately, base R doesn’t have a sensible way of automatically adding multiple regression lines to a plot and so if we want to do this, we will have to do it manually (this is easier to do in <code>ggplot</code> and this will be added to the materials later).</p>
<p>First, we create the underlying plot containing the raw data values. We did this previously, so we can just copy/paste the code for the raw data.</p>
<div class="sourceCode" id="cb245"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create a new plot based on Light ~ Depth</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>, 
     data <span class="op">=</span> <span class="va">treelight</span>, type <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span>

<span class="co"># add the Broadleaf data</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
     data <span class="op">=</span> <span class="va">broLight</span>, col <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span>

<span class="co"># add the Conifer data</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
     data <span class="op">=</span> <span class="va">conLight</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-12-1.png" width="672"></div>
<p>Then we can add the linear regression without the interaction term.</p>
<div class="sourceCode" id="cb246"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lm.add</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span> <span class="op">+</span> <span class="va">Species</span>,
             data <span class="op">=</span> <span class="va">treelight</span><span class="op">)</span></code></pre></div>
<p>We first need to extract the relative coefficient values from the <code>lm</code> object and then combine them manually to create separate vectors containing the intercept and slope coefficients for each line. This next set of command is a bit annoying but stick with it; it’ll pay dividends (no, really it will – you always secretly wanted to be a computer programmer didn’t you? This medic/biologist/life scientist thing is just a passing phase that you’ll grow out of…)</p>
<div class="sourceCode" id="cb247"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/coef.html">coef</a></span><span class="op">(</span><span class="va">lm.add</span><span class="op">)</span>
<span class="va">cf</span></code></pre></div>
<pre><code>##    (Intercept)          Depth SpeciesConifer 
##      7962.0316      -262.1656     -3113.0265</code></pre>
<div class="sourceCode" id="cb249"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cf.Broadleaf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">cf</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="va">cf</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span>
<span class="va">cf.Conifer</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">cf</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="va">cf</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>, <span class="va">cf</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span>

<span class="va">cf.Broadleaf</span></code></pre></div>
<pre><code>## (Intercept)       Depth 
##   7962.0316   -262.1656</code></pre>
<div class="sourceCode" id="cb251"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cf.Conifer</span></code></pre></div>
<pre><code>## (Intercept)       Depth 
##   4849.0051   -262.1656</code></pre>
<ul>
<li>The first line extracts the three (in this case) coefficients from the <code>lm</code> object as a vector called <code>cf</code>, and the second line prints this to the screen.</li>
<li>In the third line we take the 1st and 2nd components of <code>cf</code> and store them as the coefficients for the <code>Broadleaf</code> line in a vector called <code>cf.Broadleaf</code>
</li>
<li>The fourth line is where we do some actual calculations. Here we realise that the intercept of the conifer line is actually the sum of the 1st and 3rd values of <code>cf</code>, whereas the slope is just the 2nd value, and so we create a vector for the conifer line that reflects this.</li>
<li>The 5th and 6th lines just print these two vectors to the screen.</li>
</ul>
<p>We can now use these two vectors to add the appropriate regression lines to the existing plot. The final code then looks like this:</p>
<div class="sourceCode" id="cb253"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># create a new plot based on Light ~ Depth</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>, 
     data <span class="op">=</span> <span class="va">treelight</span>, type <span class="op">=</span> <span class="st">"n"</span><span class="op">)</span>

<span class="co"># add the Broadleaf data</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
     data <span class="op">=</span> <span class="va">broLight</span>, col <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span>

<span class="co"># add the Conifer data</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span>,
     data <span class="op">=</span> <span class="va">conLight</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span>

<span class="co"># add the Broadleaf regression line</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">cf.Broadleaf</span>, col <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span>

<span class="co"># add the Conifer regression line</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">cf.Conifer</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-15-1.png" width="672"></div>
</div>
</div>
<div id="assumptions-12" class="section level2" number="23.8">
<h2>
<span class="header-section-number">23.8</span> Assumptions<a class="anchor" aria-label="anchor" href="#assumptions-12"><i class="fas fa-link"></i></a>
</h2>
<p>In this case we first wanted to check if the interaction was significant, prior to checking the assumptions. If we would have checked the assumptions first, then we would have done that one the full model (with the interaction), then done the ANOVA if everything was OK. We would have then found out that the interaction was not significant, meaning we’d have to re-check the assumptions with the new model. In what order you do it is a bit less important here. The main thing is that you check the assumptions and report on it!</p>
<p>Anyway, hopefully you’ve got the gist of checking assumptions for linear models by now: diagnostic plots!</p>
<div class="sourceCode" id="cb254"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span> <span class="op">+</span> <span class="va">Species</span>,
        data <span class="op">=</span> <span class="va">treelight</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-16-1.png" width="672"></div>
<ul>
<li>The top left graph looks OK, no systematic pattern.</li>
<li>The top right graph isn’t perfect, but I’m happy with the normality assumption.</li>
<li>The bottom left graph is OK, some very slight suggestion of heterogeneity of variance, but nothing to be too worried about.</li>
<li>The bottom right graph shows that all of the points are OK</li>
</ul>
<p>Woohoo!</p>
</div>
<div id="dealing-with-interaction" class="section level2" number="23.9">
<h2>
<span class="header-section-number">23.9</span> Dealing with interaction<a class="anchor" aria-label="anchor" href="#dealing-with-interaction"><i class="fas fa-link"></i></a>
</h2>
<p>If there <em>had been</em> a significant interaction between the two predictor variables (for example, if light intensity had dropped off significantly faster in conifer woods than in broad leaf woods, in addition to being lower overall, then we would again be looking for two equations for the linear regression, but this time the gradients vary as well.
In this case interaction is important and so we need the output from a linear regression that explicitly includes the interaction term:</p>
<div class="sourceCode" id="cb255"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span> <span class="op">+</span> <span class="va">Species</span> <span class="op">+</span> <span class="va">Depth</span><span class="op">:</span><span class="va">Species</span>,
   data <span class="op">=</span> <span class="va">treelight</span><span class="op">)</span></code></pre></div>
<p>or written using the short-hand:</p>
<div class="sourceCode" id="cb256"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Light</span> <span class="op">~</span> <span class="va">Depth</span> <span class="op">*</span> <span class="va">Species</span>,
   data <span class="op">=</span> <span class="va">treelight</span><span class="op">)</span></code></pre></div>
<p>There really is absolutely no difference in the end result.
Either way this gives us the following output:</p>
<pre><code>## 
## Call:
## lm(formula = Light ~ Depth * Species, data = treelight)
## 
## Coefficients:
##          (Intercept)                 Depth        SpeciesConifer  
##              7798.57               -221.13              -2784.58  
## Depth:SpeciesConifer  
##               -71.04</code></pre>
<p>As before the broadleaf line is used as the baseline regression and we can read off the values for its intercept and slope directly:</p>
<p>Broadleaf:
<span class="math display">\[\begin{equation}
Light = 7798.57 + -221.13 * Depth
\end{equation}\]</span></p>
<p>Note that this is different from the previous section, by allowing for an interaction all fitted values will change.</p>
<p>For the conifer line we will have a different intercept value and a different gradient value. As before the value underneath <code>SpeciesConifer</code> gives us the difference between the intercept of the conifer line and the broad leaf line. The new, additional term <code>Depth:SpeciesConifer</code> tells us how the coefficient of <code>Depth</code> varies for the conifer line i.e. how the gradient is different. Putting these two together gives us the following equation for the line of best fit conifer woodland:</p>
<p>Conifer:
<span class="math display">\[\begin{equation}
Light = (7798.57 + -2784.58) + (-221.13 + -71.04) * Depth
\end{equation}\]</span></p>
<p><span class="math display">\[\begin{equation}
Light = 5014 + -292.2 * Depth
\end{equation}\]</span></p>
<p>These also happen to be exactly the lines of best fit that you would get by calculating a linear regression on each group’s data separately.</p>
</div>
<div id="exercise-clover-and-yarrow" class="section level2" number="23.10">
<h2>
<span class="header-section-number">23.10</span> Exercise: Clover and yarrow<a class="anchor" aria-label="anchor" href="#exercise-clover-and-yarrow"><i class="fas fa-link"></i></a>
</h2>
<div class="exercise">
<p><span id="exr:unlabeled-div-15" class="exercise"><strong>Exercise 23.1  </strong></span>Clover and yarrow field trials</p>
<p>The <code>data/raw/CS4-clover.csv</code> dataset contains information on field trials at three different farms (<code>A</code>, <code>B</code> and <code>C</code>). Each farm recorded the yield of clover in each of ten fields along with the density of yarrow stalks in each field.</p>
<ul>
<li>Investigate how clover yield is affected by yarrow stalk density. Is there evidence of competition between the two species?</li>
<li>Is there a difference between farms?</li>
</ul>
<details><summary>
Answer
</summary><div class="sourceCode" id="cb258"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">clover</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/raw/CS4-clover.csv"</span>,
                   stringsAsFactors <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p>This dataset has three variables; <code>Yield</code> (which is the response variable), <code>Yarrow</code> (which is a continuous predictor variable) and <code>Farm</code> (which is the categorical predictor variables). As always we’ll visualise the data first:</p>
<div class="sourceCode" id="cb259"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">Yield</span> <span class="op">~</span> <span class="va">Yarrow</span>,
     data <span class="op">=</span> <span class="va">clover</span>, col <span class="op">=</span> <span class="va">Farm</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-21-1.png" width="672"></div>
<p>Here, I’ve used a trick (that admittedly I probably should have told you in the practical handout) where we can use a categorical variable (here <code>Farm</code>) to specify the colours used in the plot. This trick only works for categorical variables with at most 8 levels because there are only 8 colours hard-coded into this feature. the colours are: black, red, green, blue, cyan, magenta, yellow and grey, in that order.</p>
<p>For our plot this means that farm <code>A</code> is black, farm <code>B</code> is red and farm <code>C</code> is green.</p>
<p>This method is still rather clunky and <code>ggplot</code> does a much better job in this respect. We’ll see how that works in an updated version.</p>
<p>More importantly, looking at this plot as it stands, it’s pretty clear that yarrow density has a significant effect on yield, but it’s pretty hard to see from the plot whether there is any effect of <code>Farm</code>, or whether there is any interaction. In order to work that out we’ll want to add the lines of best fit for each <code>Farm</code> separately.</p>
<div class="sourceCode" id="cb260"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">Yield</span> <span class="op">~</span> <span class="va">Yarrow</span>,
     data <span class="op">=</span> <span class="va">clover</span>, col <span class="op">=</span> <span class="va">Farm</span><span class="op">)</span>

<span class="va">farmA</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">clover</span>, subset <span class="op">=</span> <span class="op">(</span><span class="va">Farm</span> <span class="op">==</span> <span class="st">"A"</span><span class="op">)</span><span class="op">)</span>
<span class="va">farmB</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">clover</span>, subset <span class="op">=</span> <span class="op">(</span><span class="va">Farm</span> <span class="op">==</span> <span class="st">"B"</span><span class="op">)</span><span class="op">)</span>
<span class="va">farmC</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html">subset</a></span><span class="op">(</span><span class="va">clover</span>, subset <span class="op">=</span> <span class="op">(</span><span class="va">Farm</span> <span class="op">==</span> <span class="st">"C"</span><span class="op">)</span><span class="op">)</span>

<span class="va">lmA</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Yield</span> <span class="op">~</span> <span class="va">Yarrow</span>, data <span class="op">=</span> <span class="va">farmA</span><span class="op">)</span>
<span class="va">lmB</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Yield</span> <span class="op">~</span> <span class="va">Yarrow</span>, data <span class="op">=</span> <span class="va">farmB</span><span class="op">)</span>
<span class="va">lmC</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Yield</span> <span class="op">~</span> <span class="va">Yarrow</span>, data <span class="op">=</span> <span class="va">farmC</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">lmA</span>, col <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">lmB</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">lmC</span>, col <span class="op">=</span> <span class="st">"green"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-22-1.png" width="672"></div>
<p>The lines of best fit are very close together, and it looks very much as if there isn’t any interaction, but also that there isn’t any effect of <code>Farm</code>. Let’s carry out the analysis:</p>
<div class="sourceCode" id="cb261"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lm.clover</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Yield</span> <span class="op">~</span> <span class="va">Yarrow</span> <span class="op">*</span> <span class="va">Farm</span>,
                data <span class="op">=</span> <span class="va">clover</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lm.clover</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Yield
##             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## Yarrow       1 8538.3  8538.3 28.3143 1.847e-05 ***
## Farm         2    3.8     1.9  0.0063    0.9937    
## Yarrow:Farm  2  374.7   187.4  0.6213    0.5457    
## Residuals   24 7237.3   301.6                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>This confirms our suspicions from looking at the plot. There isn’t any interaction between <code>Yarrow</code> and <code>Farm.</code> <code>Yarrow</code> density has a statistically significant effect on <code>Yield</code> but there isn’t any difference between the different farms on the yields of clover.</p>
<p>Let’s check the assumptions:</p>
<div class="sourceCode" id="cb263"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">lm.clover</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-24-1.png" width="672"></div>
<p>This is a borderline case.</p>
<ol style="list-style-type: decimal">
<li>Normality is fine (Normal QQ)</li>
<li>There aren’t any highly influential points (Residuals vs Leverage)</li>
<li>There is a strong suggestion of heterogeneity of variance. Most of the points are relatively close to the lines of best fit, but the there is a much great spread of points low Yarrow density (which corresponds to high Yield values, which is what the fitted values correspond to).</li>
<li>Finally, there is a slight suggestion that the data might not be linear, that it might curve slightly.</li>
</ol>
<p>We have two options; both of which are arguably OK to do in real life.</p>
<ol style="list-style-type: decimal">
<li>We can claim that these assumptions are well enough met and just report the analysis that we’ve just done.</li>
<li>We can decide that the analysis is not appropriate and look for other options.
<ol style="list-style-type: lower-alpha">
<li>We can try to transform the data by taking logs of <code>Yield.</code> This might fix both of our problems: taking logs of the response variable has the effect of improving heterogeneity of variance when the residual vs fitted plot is more spread out on the right vs. the left (like ours). It also is appropriate if we think the true relationship between the response and predictor variables is exponential rather than linear (which we might have). We do have the capabilities to try this option.</li>
<li>We could try a permutation based approach (beyond the remit of this course, and actually a bit tricky in this situation). This wouldn’t address the non-linearity but it would deal with the variance assumption.</li>
<li>We could come up with a specific functional, mechanistic relationship between yarrow density and clover yield based upon other aspects of their biology. For example there might be a threshold effect such that for yarrow densities below a particular value, clover yields are unaffected, but as soon as yarrow values get above that threshold the clover yield decreases (maybe even linearly). This would require a much better understanding of clover-yarrow dynamics (of which I personally know very little).</li>
</ol>
</li>
</ol>
<p>Let’s do a quick little transformation of the data, and repeat our analysis see if our assumptions are better met this time (just for the hell of it):</p>
<div class="sourceCode" id="cb264"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">Yield</span><span class="op">)</span> <span class="op">~</span> <span class="va">Yarrow</span>,
     data <span class="op">=</span> <span class="va">clover</span>, col <span class="op">=</span> <span class="va">Farm</span><span class="op">)</span>

<span class="va">lmlogA</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">Yield</span><span class="op">)</span> <span class="op">~</span> <span class="va">Yarrow</span>, data <span class="op">=</span> <span class="va">farmA</span><span class="op">)</span>
<span class="va">lmlogB</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">Yield</span><span class="op">)</span> <span class="op">~</span> <span class="va">Yarrow</span>, data <span class="op">=</span> <span class="va">farmB</span><span class="op">)</span>
<span class="va">lmlogC</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">Yield</span><span class="op">)</span> <span class="op">~</span> <span class="va">Yarrow</span>, data <span class="op">=</span> <span class="va">farmC</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">lmlogA</span>, col <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">lmlogB</span>, col <span class="op">=</span> <span class="st">"red"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/abline.html">abline</a></span><span class="op">(</span><span class="va">lmlogC</span>, col <span class="op">=</span> <span class="st">"green"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-25-1.png" width="672"></div>
<p>Again, this looks plausible. There’s a noticeable outlier from Farm B (red point at the bottom of the plot) but otherwise we see that: there probably isn’t an interaction; there is likely to be an effect of <code>Yarrow</code> on <code><a href="https://rdrr.io/r/base/Log.html">log(Yield)</a></code>; and there probably isn’t any difference between the farms.</p>
<p>Let’s do the analysis:</p>
<div class="sourceCode" id="cb265"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">lm.log</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">Yield</span><span class="op">)</span> <span class="op">~</span> <span class="va">Yarrow</span> <span class="op">*</span> <span class="va">Farm</span>,
             data <span class="op">=</span> <span class="va">clover</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">lm.log</span><span class="op">)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: log(Yield)
##             Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
## Yarrow       1 10.6815 10.6815 27.3233 2.34e-05 ***
## Farm         2  0.0862  0.0431  0.1103   0.8960    
## Yarrow:Farm  2  0.8397  0.4199  1.0740   0.3575    
## Residuals   24  9.3823  0.3909                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
<p>Woop. All good so far. We have the same conclusions as before in terms of what is significant and what isn’t. Now we just need to check the assumptions:</p>
<div class="sourceCode" id="cb267"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span><span class="op">(</span>mfrow <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">lm.log</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="cs4-practical-linear_regression_grouped_data_files/figure-html/unnamed-chunk-27-1.png" width="672"></div>
<p>Well, this is actually a better set of diagnostic plots. Whilst point number 12 is a clear outlier, if we ignore that point then all of the rest of the plots do look better.</p>
<p>So now we know that <code>Yarrow</code> is a significant predictor of <code>Yield</code> and we’re happy that the assumptions have been met.</p>
</details>
</div>
</div>
<div id="key-points-7" class="section level2" number="23.11">
<h2>
<span class="header-section-number">23.11</span> Key points<a class="anchor" aria-label="anchor" href="#key-points-7"><i class="fas fa-link"></i></a>
</h2>
<div class="keypoints">
<ul>
<li>A linear regression analysis with grouped data is used when we have one categorical and one continuous predictor variable, together with one continuous response variable</li>
<li>We can visualise the data by plotting a line of best fit together with the raw data</li>
<li>When performing an ANOVA, we need to check for interaction terms</li>
<li>Again, we check the underlying assumptions using diagnostic plots</li>
<li>We can create an equation for the line of best fit for each group in the data using the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> output</li>
</ul>
</div>

</div>
</div>



  <div class="chapter-nav">
<div class="prev"><a href="two-way-anova.html"><span class="header-section-number">22</span> Two-way ANOVA</a></div>
<div class="next"><a href="cs5-intro.html"><span class="header-section-number">24</span> Introduction</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#linear-regression-with-grouped-data"><span class="header-section-number">23</span> Linear regression with grouped data</a></li>
<li><a class="nav-link" href="#objectives-11"><span class="header-section-number">23.1</span> Objectives</a></li>
<li><a class="nav-link" href="#purpose-and-aim-7"><span class="header-section-number">23.2</span> Purpose and aim</a></li>
<li><a class="nav-link" href="#section-commands-11"><span class="header-section-number">23.3</span> Section commands</a></li>
<li><a class="nav-link" href="#data-and-hypotheses-10"><span class="header-section-number">23.4</span> Data and hypotheses</a></li>
<li><a class="nav-link" href="#summarise-and-visualise-10"><span class="header-section-number">23.5</span> Summarise and visualise</a></li>
<li><a class="nav-link" href="#implement-the-test-5"><span class="header-section-number">23.6</span> Implement the test</a></li>
<li>
<a class="nav-link" href="#interpret-output-and-present-results-1"><span class="header-section-number">23.7</span> Interpret output and present results</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#finding-intercept-values"><span class="header-section-number">23.7.1</span> Finding intercept values</a></li>
<li><a class="nav-link" href="#adding-multiple-regression-lines"><span class="header-section-number">23.7.2</span> Adding multiple regression lines</a></li>
</ul>
</li>
<li><a class="nav-link" href="#assumptions-12"><span class="header-section-number">23.8</span> Assumptions</a></li>
<li><a class="nav-link" href="#dealing-with-interaction"><span class="header-section-number">23.9</span> Dealing with interaction</a></li>
<li><a class="nav-link" href="#exercise-clover-and-yarrow"><span class="header-section-number">23.10</span> Exercise: Clover and yarrow</a></li>
<li><a class="nav-link" href="#key-points-7"><span class="header-section-number">23.11</span> Key points</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

					</div>
				</div>
				<!-- Related links -->
				<!--<div class="campl-column3 campl-secondary-content">
					<div class="campl-content-container">
						<div class="campl-heading-container">
							<h2>Related Links</h2>
						</div>
						<ul class='campl-unstyled-list campl-related-links'>
							<li><a href="#">Lorem ipsum dolor sit amet</a></li>
							<li><a href="#">Consectetur adipisicing elit</a></li>
							<li><a href="#">Sed do eiusmod tempor incididunt extra long wrapping on to two line</a></li>
							<li><a href="#">Labore et dolore magna aliqua</a></li>
							<li><a href="#">Ut enim ad minim veniam</a></li>
							<li><a href="#">Quis nostrud exercitation ullamco</a></li>
						</ul>
					</div>
					<div class="campl-content-container">
						<div class="campl-vertical-teaser campl-teaser campl-promo-teaser">
							<div class="campl-content-container campl-vertical-teaser-txt">
								<p class='campl-teaser-title'><a href="#">Promo teaser with title above</a></p>
							</div>
							<div class="campl-content-container campl-vertical-teaser-img">
								<a href="#" class="campl-teaser-img-link"><img alt=""  src="images/content/homepage-promo-placeholder.png" class="campl-scale-with-grid" /></a>
							</div>
							<div class="campl-content-container campl-vertical-teaser-txt clearfix">
								<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
								<a href="#4" class="campl-secondary-cta campl-float-right">Read more</a>
							</div>
						</div>
					</div>
				</div>-->
			</div>
		</div>
		<div class="campl-row campl-local-footer">
			<div class="campl-wrap clearfix">
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Contact us</h3>
						 <div class="content">
						   <p>Bioinformatics Training Department of Genetics University of Cambridge Downing Street Cambridge CB2 3EH United Kingdom</p>
						   <h3>Contact:</h3> <a href="mailto:%20bioinfotraining@bio.cam.ac.uk">bioinfotraining@bio.cam.ac.uk</a>
						 </div>
					</div>
				</div>
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Bioinformatics Training</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/undergraduate">Undergraduate training</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate">Postgraduate training</a>
							</li>
						</ul>
</div>
				</div>
				<div class="campl-column3 campl-footer-navigation">
					<div class="campl-content-container campl-navigation-list">
						<h3>Postgraduate Courses by Theme</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/programming">Basic Skills and Programming</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/services">Databases and Services</a>
							</li>
							<li>
							  <a href="https://bioinfotraining.bio.cam.ac.uk/postgraduate/specialized">Specialised Topics</a>
							</li>
						</ul>
</div>
				</div>
				<div class="campl-column3 campl-footer-navigation last">
					<div class="campl-content-container campl-navigation-list">
						<h3>About Bioinformatics Training</h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about">About the Facility</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about/findus">How to find us</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/about/visitors">Visiting Cambridge</a>
							</li>
							<li>
								<a href="https://bioinfotraining.bio.cam.ac.uk/privacy-and-cookie-policies">Privacy and Cookies policy</a>
							</li>
						</ul>
</div>
				</div>
			</div>
		</div>
	<div class="campl-row campl-global-footer">
		<div class="campl-wrap clearfix">
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-footer-logo">
					<img alt="University of Cambridge" src="images/interface/main-logo-small.png" height="38px;" class="campl-scale-with-grid"><p>© 2021 University of Cambridge</p>
						<ul class="campl-unstyled-list campl-global-footer-links">
<li>
								<a href="http://www.cam.ac.uk/university-a-z">University A-Z</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/contact-the-university">Contact the University</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-this-site/accessibility">Accessibility</a>
							</li>
							<li>
								<a href="http://www.admin.cam.ac.uk/univ/information/foi/">Freedom of information</a>
							</li>
							<li>
								<a href="http://www.cam.ac.uk/about-this-site/terms-and-conditions">Terms and conditions</a>
							</li>
						</ul>
</div>
			</div>
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-navigation-list">

					<div class="link-list">
						<h3><a href="http://www.cam.ac.uk/study-at-cambridge">Study at Cambridge</a></h3>
						<ul class="campl-unstyled-list">
<li>
								<a href="http://www.study.cam.ac.uk/undergraduate/">Undergraduate</a>
							</li>
							<li>
								<a href="http://www.graduate.study.cam.ac.uk/">Graduate</a>
							</li>
							<li>
								<a href="http://www.internationalstudents.cam.ac.uk">International students</a>
							</li>
							<li>
								<a href="http://www.ice.cam.ac.uk">Continuing education</a>
							</li>
							<li>
								<a href="http://www.epe.admin.cam.ac.uk/">Executive and professional education</a>
							</li>
							<li>
								<a href="http://www.educ.cam.ac.uk">Courses in education</a>
							</li>
						</ul>
</div>
				</div>
			</div>
			<div class="campl-column3 campl-footer-navigation">
				<div class="campl-content-container campl-navigation-list">
					<h3><a href="http://www.cam.ac.uk/about-the-university">About the University</a></h3>
					<ul class="campl-unstyled-list campl-page-children">
<li>
							<a href="http://www.cam.ac.uk/about-the-university/how-the-university-and-colleges-work">How the University and Colleges work</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/about-the-university/visiting-the-university">Visiting the University</a>
						</li>
						<li>
							<a href="http://map.cam.ac.uk">Map</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/news">News</a>
						</li>
						<li>
							<a href="http://www.admin.cam.ac.uk/whatson/">Events</a>
						</li>
						<li>
							<a href="http://www.jobs.cam.ac.uk">Jobs</a>
						</li>
						<li>
							<a href="https://www.philanthropy.cam.ac.uk/">Give to Cambridge</a>
						</li>
					</ul>
</div>
			</div>
			<div class="campl-column3 campl-footer-navigation last">
				<div class="campl-content-container campl-navigation-list">
					<h3><a href="http://www.cam.ac.uk/research">Research at Cambridge</a></h3>
					<ul class="campl-unstyled-list">
<li>
							<a href="http://www.cam.ac.uk/research/news">News</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/features">Features</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/discussion">Discussion</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/spotlight-on">Spotlight on...</a>
						</li>
						<li>
							<a href="http://www.cam.ac.uk/research/research-at-cambridge">About research at Cambridge</a>
						</li>
					</ul>
</div>
			</div>
		</div>
	</div>
	<!-- .campl-global-footer ends -->

<!--[if lte IE 8]>
</div>
<![endif]-->

	<script type="text/javascript" src="javascripts/libs/ios-orientationchange-fix.js"></script><script type="text/javascript" src="javascripts/libs/jquery-min.js"></script><script type="text/javascript" src="javascripts/libs/modernizr.js"></script><script type="text/javascript" src="javascripts/custom.js"></script><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
